Page type snippet
prismicio/slice-machine pull request #1012
Opened 2023-06-15 16:07 UTC by hypervillain

https://linear.app/prismic/issue/DT-1403/aauser-i-can-see-the-header-of-the-custom-type-and-page-type-builder

Implemented a `MainContainer` and its Header, used in both Custom type and Page type builders. The Page type builder now contains a "Page snippet" button. It opens a Dialog that displays placeholder text.

2023-06-16 15:06 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.stories.tsx
> +    docs: { story: { height: 256 * 2, inline: false } },
💡 Try to remove it?

2023-06-16 15:06 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/Header/Header.tsx
> +  Actions?: ReactElement[];
💡 Personally I always use `ReactNode`, but don't know if it's better.

2023-06-16 15:06 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/Header/Header.css.ts
> +export const flex = style([
💡 `spaceBetween`?

2023-06-20 12:46 UTC, bapmrl commented
Completes DT-1403 and DT-1404.

2023-06-20 15:44 UTC, bapmrl requested changes
Nice work 😊

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/components/AppLayout/index.tsx
> +          "& > :first-child": {
❓ Have we checked it works on all pages (and there's only ever one child)?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/lib/builders/CustomTypeBuilder/index.tsx
> -import Container from "@components/Container";
⚠️ The `@components/Container` is no longer used and should be deleted to avoid accumulating dead code.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/lib/builders/CustomTypeBuilder/index.tsx
>      <Box sx={{ flex: 1 }}>
❓ Is this extra `Box` necessary?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +  const { currentCustomType, hasPendingModifications, isSavingCustomType } =
❓ What is the difference between `customType` and `currentCustomType`? If they are the same, we could probably avoid the extra `if (currentCustomType === null)` condition.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/Header/Header.tsx
> +  actions?: ReactElement[];
💡 It would probably be more "natural" to be able to pass a `ReactNode` instead. That way, we could pass just one element or a React `Fragment`.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +      save
❓ Shouldn't it be `Save`?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +        backTo={() => void router.push(config.tablePagePathname)}
❓ Would https://nextjs.org/docs/pages/api-reference/functions/use-router#routerback be better suited? Would it remove the need to pass the `backTo` prop altogether?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +  return `Create a new page component in your  pages  directory with the filename  [uid].jsx . (If you already have a file with that name, you can create the file
❓ Were the double spaces `  ` added on purpose?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +function wait(milliseconds: number) {
💡 You don't have to change it, but one little advice: most people would expect the `PageTypeSnippet` component to appear first as it's the main export of this file. Then, functions, constants, etcetera could appear in "order of reading" from top to bottom.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +const PluginPageTypeSnippet = () => {
⚠️ This component doesn't bring much value and the style could directly be applied in `PageTypeSnippet`.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +  const content = useRequest(getPageTypeSnippet, []);
⚠️ It would be better to write a `usePageTypeSnippet` hook like: 
https://github.com/prismicio/slice-machine/blob/5cd4d26b4d37715173202c27ed3bf1dd6ac669ff/packages/slice-machine/src/features/customTypes/customTypesTable/useCustomTypes.ts#L18
Thay way, we could easily extract it in the future, if need be.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +          key="open-snippet"
⚠️ Don't add unnecessary `key`s.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +export const PageTypeSnippet = () => {
💡 Maybe `PageTypeSnippetButton` would better show that a button will be displayed when using this component?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +      <DialogHeader icon="add" title="Page Snippet" />
❓ "Page Snippet" or "Page snippet"?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +                  marginBottom: vars.size[32],
❓ What is the purpose of this `marginBottom`?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/Header/Header.tsx
> +export const Header = ({ actions, backTo, breadcrumb }: HeaderProps) => (
💡 There's not a lot of code so `Header` probably doesn't warrant its own directory. Here, it's fine, but doing that too much can increase the likelihood of duplicating code and styles (like @xrutayisire experienced when he worked on the `Table` component).

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.tsx
> +  className?: string;
❓ Why add unused props? We're not implementing a library of reusable components (reusable outside of Slice Machine).

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.tsx
> +export const MainContainer: FC<MainContainerProps> = ({
💡 A shorter version could be:
```
export const MainContainer: FC<MainContainerProps> = (props) => <div {...props} />
```

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.tsx
> +export const MainContainerContent: FC<PropsWithChildren> = ({ children }) => (
💡 It's not "natural" to read `MainContainerContent` before `MainContainer`.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/Header/Header.css.ts
> +    justifyContent: "space-between",
⚠️ I don't think you need `justifyContent: "space-between"` so `spaceBetweenFlex` wouldn't be a good name. Maybe `navigation` would be a good name?

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/Header/Header.css.ts
> +export const spaceBetweenFlex = style([
💡 No need to call `style` here.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.stories.tsx
> +import { MainContainer, MainContainerHeader, MainContainerContent } from "./";
💡 Using `./` is confusing. I would recommend using the real relative path.

2023-06-20 15:44 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.stories.tsx
> +            <Button key="action-1">Action 1</Button>,
💡 I don't think `key`s are necessary here.

2023-06-27 15:11 UTC, hypervillain commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +  const { currentCustomType, hasPendingModifications, isSavingCustomType } =
`currentCustomType` is the CT selected in Redux to be manipulated later in the CT builder. They could be merged once we move away from Redux or by passing down `customType` to children. But the calls to Redux are nested deep down so it's not an easy change

2023-06-27 16:00 UTC, hypervillain commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +        backTo={() => void router.push(config.tablePagePathname)}
you can come from URL history on browser and therefore not have a previous place to go back to

2023-06-27 16:00 UTC, hypervillain commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +  return `Create a new page component in your  pages  directory with the filename  [uid].jsx . (If you already have a file with that name, you can create the file
It's "fake" code!

2023-06-27 16:03 UTC, hypervillain commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +      <DialogHeader icon="add" title="Page Snippet" />
"Page Snippet" in the design!

2023-06-27 16:12 UTC, hypervillain commented on packages/slice-machine/src/components/MainContainer/MainContainer.stories.tsx
> +import { MainContainer, MainContainerHeader, MainContainerContent } from "./";
I think the opposite: everything that you can and are allowed to access from a story is what's exported from index, with its definitive name also

2023-06-28 13:48 UTC, hypervillain commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/PageTypeSnippet.tsx
> +function wait(milliseconds: number) {
I understand, I'm used to do the exact opposite usually: the parent component is down, and everything used by it is on top of it. Opposite mental model I guess, I'll update anyway

2023-06-28 14:00 UTC, hypervillain commented on packages/slice-machine/components/AppLayout/index.tsx
> +          "& > :first-child": {
It does not seem to break anything. But this can probably be done differently? I could not find how but we could discuss it

2023-06-30 08:14 UTC, bapmrl commented
Continued in https://github.com/prismicio/slice-machine/pull/1019.

2023-06-30 08:14 UTC, closed without merging