Page type snippet markdown
prismicio/slice-machine pull request #1019
Opened 2023-06-23 07:54 UTC by hypervillain

Follows #1012, adds Markdown renderer and optional "documentation:read" hook to manager. Renders Page type snippets in a Dialog

2023-06-26 14:08 UTC, lihbr commented on packages/plugin-kit/src/index.ts
> +} from "./hooks/documentation-read";
I'd add "Documentation" as an export also

2023-06-26 14:08 UTC, lihbr commented on package.json
> +    "unist-util-visit": "^4.1.2"
Don't install package-dependencies top level! (unless I'm missing the reason)

2023-06-26 14:08 UTC, lihbr commented on packages/manager/src/managers/documentation/DocumentationManager.ts
> +};
Exactly why I'm suggesting exporting that from the plugin kit so you don't have to recreate it here :)

2023-06-26 14:08 UTC, lihbr commented on packages/manager/src/managers/documentation/DocumentationManager.ts
> +	documentation: Documentation | Documentation[] | undefined;
For convenience, non array should be casted to array, so that return type can simply be `documentation: Documentation[]` (always defined), makes using the hook much more straightforward after that.

See the `SnippetManager` code for example: https://github.com/prismicio/slice-machine/blob/1ffb8cff5f38e82be9f534c9a2a249666af2b7a4/packages/manager/src/managers/snippets/SnippetsManager.ts#L20-L45

2023-06-26 14:08 UTC, lihbr commented on packages/manager/src/managers/documentation/DocumentationManager.ts
> +	}
Does this ever throw? Not sure it does 🤔

2023-06-26 14:08 UTC, lihbr commented on packages/manager/src/managers/documentation/DocumentationManager.ts
> +				documentation: data,
I think data is an array of results, so you'll nee to flatten it like in the `SnippetManager`: https://github.com/prismicio/slice-machine/blob/1ffb8cff5f38e82be9f534c9a2a249666af2b7a4/packages/manager/src/managers/snippets/SnippetsManager.ts#L20-L45

2023-06-26 16:29 UTC, hypervillain commented on package.json
> +    "unist-util-visit": "^4.1.2"
wrong package.json 😬

2023-06-27 11:01 UTC, hypervillain commented on packages/manager/src/managers/documentation/DocumentationManager.ts
> +	}
If the hook is not implemented, right?

2023-06-30 08:25 UTC, bapmrl commented
Completes DT-1401, DT-1403, DT-1404 and DT-1405.

2023-06-30 10:06 UTC, bapmrl requested changes

2023-06-30 10:06 UTC, bapmrl commented on packages/plugin-kit/src/hooks/documentation-read.ts
> +	label?: string;
❓ Why is the `label` optional? Does it mean documentation could be used outside of tabs?

2023-06-30 10:06 UTC, bapmrl commented on packages/plugin-kit/src/hooks/documentation-read.ts
> +export type DocumentationReadHookReturnType = Documentation[] | undefined;
💡 @lihbr and @hypervillain, why return `undefined` when there's no documentation? Why not just return an empty array?

2023-06-30 10:06 UTC, bapmrl commented on packages/adapter-next/src/hooks/documentation-read.ts
> +				content: md,
💡 Why not use `stripIndent` (or maybe `source`?) from `common-tags` to inline the `content`? It's a pattern that's been used in multiple other files and it would prevent having to declare as many `const md` as there are elements in the returned arrays.

2023-06-30 10:06 UTC, bapmrl commented on packages/slice-machine/package.json
> -    "puppeteer": "^19.11.1",
⚠️ `puppeteer` shouldn't be removed from the `dependencies`, otherwise the "Take a screenshot" feature won't work in production.

2023-06-30 10:06 UTC, bapmrl commented on packages/slice-machine/package.json
> +    "hast-util-to-string": "^2.0.0",
⚠️ This dependency doesn't appear to be used in `slice-machine-ui` and should be removed.

2023-06-30 10:06 UTC, bapmrl commented on packages/slice-machine/package.json
> +    "react-syntax-highlighter": "15.5.0",
⚠️ For the sake of consistency, this should use `^` as it's a dependency.

2023-06-30 10:06 UTC, bapmrl commented on packages/slice-machine/package.json
> +    "remark-directive": "^2.0.1",
⚠️ This dependency doesn't appear to be used in `slice-machine-ui` and should be removed.

2023-06-30 10:06 UTC, bapmrl commented on packages/manager/src/managers/documentation/DocumentationManager.ts
> +	}
⚠️ I don't think it throws (look at `CustomTypesManager` for instance). You can remove the `try`/`catch`.

2023-06-30 10:06 UTC, bapmrl commented on packages/manager/test/SliceMachineManager-documentation-read.test.ts
> +it("calls plugins' `slice:create` hook", async (ctx) => {
⚠️ `documentation:read`.

2023-06-30 10:20 UTC, hypervillain commented on packages/plugin-kit/src/hooks/documentation-read.ts
> +	label?: string;
Yes, if there is only one documentation page, no tabs are displayed, and the label is therefore not used

2023-06-30 10:21 UTC, hypervillain commented on packages/plugin-kit/src/hooks/documentation-read.ts
> +export type DocumentationReadHookReturnType = Documentation[] | undefined;
Good catch, it's actually empty array

2023-06-30 10:21 UTC, hypervillain commented on packages/adapter-next/src/hooks/documentation-read.ts
> +				content: md,
I agree but this is fake content, I'll let @angeloashmore and @lihbr decide how they want to take care of it

2023-06-30 10:44 UTC, xrutayisire commented on packages/slice-machine/package.json
> -    "puppeteer": "^19.11.1",
My bad on this one, the merge with conflicts took too much time (1 hour 🥵), so I planned to rely on you guys to check this 😬

2023-06-30 12:49 UTC, bapmrl commented on packages/plugin-kit/src/hooks/documentation-read.ts
> +	label?: string;
Okay, I understand. Thanks!

2023-06-30 14:50 UTC, bapmrl requested changes
I'm sorry, but this Pull Request is too big and I'll have to continue commenting Monday morning. Here's a second set of comments.

2023-06-30 14:50 UTC, bapmrl commented on packages/adapter-next/src/hooks/documentation-read.ts
> +	return undefined;
❓ Should it be `[]` as you removed `undefined` from the hook's return type?

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/icons/FileIcons.tsx
> +export const Typescript: FC = () => (
⚠️ I think it can be confusing to mix multiple icons into a single file. Indeed, it makes it harder to quickly know what icons are available just by checking the contents of the `icons` folder.

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/icons/FileIcons.tsx
> +export const Javascript: FC = () => (
💡 "TypeScript" and "JavaScript" are written with a capital "S".

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/components/MainContainer/MainContainer.stories.tsx
> +              <Button key="action-1">Action 1</Button>
❓ I don't understand why we need to pass React `key`s here.

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +        backTo={() => void router.push(config.tablePagePathname)}
💡 We can fix that later, but there's a software design issue. `MainContainerHeader` has too many responsibilities. We could create a "connected" component that would handle navigation for us. That component could be located in a `core/navigation` folder and would use `Breadcrumb` and `Button`. It would implement the behavior and use the browser's `history` API to know whether we're allowed to call `router.back` or not. When not allowed (because the history is empty), the button could be `disabled`. But let's discuss this again at a later point so that we can merge this Pull Request 🙂

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/features/documentation/useDocumentation.ts
> +} from "@slicemachine/plugin-kit";
⚠️ We should not import `@slicemachine/plugin-kit`. It's not part of `slice-machine-ui`'s `dependencies` and we probably don't want to add it. Adding it would increase the number of relationships between workspaces and blurrying the overall architecture of the project. I think the front end should not be aware of the plugin system (at least, it's my understanding of what DevX proposed).

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/features/documentation/useDocumentation.ts
> +  const args = JSON.parse(str) as DocumentationReadHookData;
⚠️ Why call `JSON.stringify` and then `JSON.parse`? It's so complicated and makes the code very hard to understand for other people. Let's be more explicit and pass a limited set of well typed arguments.

2023-06-30 14:50 UTC, bapmrl commented on packages/slice-machine/src/features/documentation/useDocumentation.ts
> +  if (errors.length > 0 || documentation.length === 0) {
❓ Why throw and potentially invalidate the cache if there's no documentation? What do we want to do UX-wise? Maybe when there's no documentation, we should simply render a message explaining that we can't provide snippets for the currently used adapter?

2023-06-30 15:33 UTC, hypervillain commented on packages/adapter-next/src/hooks/documentation-read.ts
> +	return undefined;
It does not really matter as it is decoded by the DocumentationManager, but it's maybe more accurate yes

2023-06-30 15:41 UTC, hypervillain commented on packages/slice-machine/src/features/customTypes/customTypesBuilder/CustomTypesBuilderPage.tsx
> +        backTo={() => void router.push(config.tablePagePathname)}
The button should not be disabled if no history is empty, it should still redirect to the table of customTypes. It does not mean we can move it to `core/navigation` of course, but right now the behaviour is correct. Maybe it's outside the scope of this PR

2023-06-30 15:56 UTC, hypervillain commented on packages/slice-machine/src/features/documentation/useDocumentation.ts
> +  if (errors.length > 0 || documentation.length === 0) {
We want to hide the button when there is no documentation for the moment. But I should be able to display nothing without throwing to not re-fetch the documentation each time users go on the page

2023-06-30 16:18 UTC, hypervillain commented on packages/slice-machine/src/features/documentation/useDocumentation.ts
> +} from "@slicemachine/plugin-kit";
Ah you're right. My bad. I've removed typings to let TypeScript resolve the types correctly (with the JSON parsing of the argument, which is ugly indeed, as I don't see how to change that fast)

2023-06-30 16:19 UTC, hypervillain commented on packages/slice-machine/src/features/documentation/useDocumentation.ts
> +  const args = JSON.parse(str) as DocumentationReadHookData;
From my understanding, useRequest is too limited to use objects and needs strings to behave properly

2023-07-03 14:21 UTC, bapmrl approved these changes

2023-07-04 14:56 UTC, lihbr commented
Some issues I encountered:

<details>
<summary>1/ Vue syntax is not recognized</summary>
<br />

![image](https://github.com/prismicio/slice-machine/assets/25330882/f97d1cee-0277-4b4f-91f3-9d94a5a746b2)

</details>

<details>
<summary>2/ Inline code blocks are not styled as such</summary>
<br />

![image](https://github.com/prismicio/slice-machine/assets/25330882/0e7b64d9-65f3-4d65-b223-85995518f9da)

</details>

<details>
<summary>3/ Line numbers are not aligned when the number of digits increases with Vue (I assume it's because it's not highlighted)</summary>
<br />

![image](https://github.com/prismicio/slice-machine/assets/25330882/265cbeac-637a-453b-8766-bbd5bf10c740)

</details>

<details>
<summary>4/ Blockquotes are not styled</summary>
<br />

![image](https://github.com/prismicio/slice-machine/assets/25330882/d0f501e1-5af2-44e6-baaa-08ba8e209b6a)

Markdown blockquote: https://www.markdownguide.org/basic-syntax/#blockquotes-1
</details>

2023-07-04 15:00 UTC, hypervillain commented
I think adding Vue syntax would simply require you to add `SyntaxHighlighter.registerLanguage("vue", vue);` next to the tsx one

2023-07-06 13:32 UTC, merged