track copy code snippet
prismicio/slice-machine pull request #1057
Opened 2023-07-17 16:01 UTC by hypervillain

Completes https://linear.app/prismic/issue/DT-1466/aapm-i-can-track-the-usage-of-code-snippets

2023-07-17 16:09 UTC, xrutayisire requested changes
Not sure about how to handle the properties. We should ask Côme.

2023-07-17 16:09 UTC, xrutayisire commented on packages/slice-machine/src/features/documentation/MarkdownRenderer/index.tsx
> +        framework: adapter,
Sorry, I just realized also, but the issue says adapter and framework. Here and in the previous event, we are mixing the two :/

2023-07-17 16:41 UTC, xrutayisire commented
Also, you didn't create your branch from an up-to-date version of dev-next-release. Maybe best would be to be up-to-date.

2023-07-18 09:03 UTC, hypervillain commented on packages/slice-machine/src/features/documentation/MarkdownRenderer/index.tsx
> +        framework: adapter,
although we call them adapters in SM, we've called it framework in Amplitude. A bit weird, but I think it's easier to check for PMs

2023-07-18 10:53 UTC, xrutayisire commented on packages/slice-machine/src/features/documentation/MarkdownRenderer/index.tsx
> +        framework: adapter,
Ok if you can confirm with Côme before the exact thing we will give since it's not what we have in the issue :/

2023-07-18 10:54 UTC, xrutayisire commented
Could you add the repository in the property so it's tracked later on? As discussed in the thread

2023-07-19 08:59 UTC, xrutayisire approved these changes
LGTM 👍

2023-07-19 09:49 UTC, xrutayisire requested changes
Just saw the little thing

2023-07-19 09:49 UTC, xrutayisire commented on packages/manager/src/managers/telemetry/types.ts
> +	{ framework: string; repository: string }
```suggestion
	{ framework: string; }
```

No need then finally

2023-07-19 12:07 UTC, merged