chore(e2e): setup project
prismicio/slice-machine pull request #1138
Opened 2023-09-13 12:10 UTC by lihbr

## Context

We want to enable users to upgrade old composite/legacy slices to shared slices managed with Slice Machine, allowing us to move toward the online custom type builder full retirement.

## The Solution

### Init

The init command now downloads remote custom types and creates them locally so they can be managed by Slice Machine if:
1. The repository selected is an existing repository
2. There's no custom type already available locally

#### Checklist

- [x] Implementation
- [x] Test

### Manager

The slice manager now has a new method `convertLegacySliceToSharedSlice()`. It takes in the composite slice model, information about the source and destination of this slice for the conversion process to happen.

#### Checklist

- [x] Implementation
- [ ] Test

### UI

The UI now display a button to convert composite slices to shared slices on the custom type builder. It opens up a model guiding users through this process.

#### Checklist

- [x] Logic
- [ ] Design
- [ ] Tracking

## Impact / Dependencies

## Checklist before requesting a review
- [ ] I hereby declare my code ready for review.
- x ] If it is a critical feature, I have added tests.
- [x] The CI is successful.
- [x] If there could backward compatibility issues, it has been discussed and planned.

## Preview

https://www.loom.com/share/1106f12be08f452fa9d555348a9438fc?sid=83e2ee93-03eb-4ec2-8810-78e9d730792e

2023-09-21 09:33 UTC, lihbr commented
- [ ] Remove CI edits before merging

2023-10-09 08:48 UTC, bapmrl requested changes
Excellent work 😍

Don't worry, I've added 40 comments and I know it's a lot... I don't want you to make a heart attack and a lot of them are just questions. I've tried to put priorities using the following icons: ⚠️, 💡 and ❓.

Let's have a call to quickly go through the comments if you want 😊

2023-10-09 08:48 UTC, bapmrl commented on .github/workflows/ci.yml
> +    if: startsWith(github.ref, 'refs/heads/lh') # Job only runs on dev branches
⚠️ I'm pretty sure you are aware of that, but the two changes to `.github/workflows/ci.yml` should be reverted to avoid breaking the `deployment` job.

2023-10-09 08:48 UTC, bapmrl commented on package.json
> +    "dev:e2e-next": "cd ./e2e-projects/next-upgrade && yarn dev --port 8000",
💡 Maybe this change should be reverted before merging as it won't be the most commonly used project during development?

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/package.json
> +    "typescript": "5.1.6"
❓ What do you think of ensuring each dependency has a single version within our monorepo? I think it would be easier to maintain (avoiding combinatorial issues) and easier to track what features we can use or not when we develop (for instance, why should we be able to use the new `satisfies` operator only in the new `e2e-projects/next-upgrade`?).

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/package.json
> +    "next": "13.4.17",
❓ What do you think of using only `^` ranges for all `dependencies` and strict versions for all `devDependencies`? It's what's been done lately for consistency.

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/package.json
> +    "slicemachine": "start-slicemachine"
❓ Should we set the `NODE_ENV=development SM_ENV=staging` environment variables like in the other `e2e-projects/next` project?

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/package.json
> +    "@types/node": "20.5.0",
💡 I would tend to move `@types/*` and other development specific dependencies to `devDependencies`, no?

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
💡 I'm okay to have specific configuration files in each workspace for now, but I think we should discuss what we would like to do in the future ^^ I think it's a lot of work to handle so many small variations in a monorepo.

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/tsconfig.json
> +{
❓ I thought Next.js was coming with its own TypeScript configuration and there was no need to define it in userland?

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/slicemachine.config.json
> +  "___repositoryName": "inspiring-briouat-syt67g",
❓ Why is there multiple repository names? They should probably be removed before merging (or a comment should be added to explain the intent).

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/app/slice-simulator/page.tsx
> +import { components } from "../../slices";
⚠️ I couldn't find the `slices` folder. Is it intended?

2023-10-09 08:48 UTC, bapmrl commented on e2e-projects/next-upgrade/customtypes/kitchen_sink/index.json
> +{
❓ What is the intent behind having these custom types? I didn't find any legacy slice inside them (maybe I should refresh my memory if I missed them :p). Are there some legacy slices in the remote Prismic repository?

2023-10-09 08:48 UTC, bapmrl commented on packages/init/src/SliceMachineInitProcess.ts
> +									task.skip("Types already exists");
⚠️ Typo: `Types already exist`.

2023-10-09 08:48 UTC, bapmrl commented on packages/init/test/SliceMachineInitProcess-syncDataWithPrismic.test.ts
> +it("skips pulling types if types already exists locally", async (ctx) => {
⚠️ Typo: "types already exist".

2023-10-09 08:48 UTC, bapmrl commented on packages/manager/src/managers/slices/SlicesManager.ts
> +			description: args.dest.variationName,
❓ Does it make sense to use `variationName` as a `description`? Maybe it should be left empty?

2023-10-09 08:48 UTC, bapmrl commented on packages/manager/src/managers/slices/SlicesManager.ts
> +					legacyPaths: {
❓ What is the purpose of `legacyPaths`?

2023-10-09 08:48 UTC, bapmrl commented on packages/manager/src/managers/slices/SlicesManager.ts
> +			}
⚠️ I'm not sure I understand the `else` case. What happens when `maybeVariation` is truthy? Does it mean the slice as already been converted and we just change `legacyPaths`? Maybe a comment could help clarify the intent.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/src/features/slices/sliceCards/NonSharedSliceViewCard.tsx
> +  path: {
💡 This type is also defined inline in `packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts`. Maybe it could be extracted to its own named typed and imported from there?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/index.tsx
> +export { ConvertLegacySliceModal } from "./ConvertLegacySliceModal";
⚠️ We would like to put new code in `src/features/*` (and in this case `src/features/slices/???`).

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/src/features/slices/sliceCards/NonSharedSliceViewCard.tsx
> +      <ConvertLegacySliceModal slice={slice} path={path} />
⚠️ I think the name of that component is a bit misleading. The first thing it renders is a `Button` than itself triggers a `DropdownMenu`. I think `ConvertLegacySliceButton` would better reflect what it is.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/index.tsx
> +      else if (typeof value.type === "string") {
💡 Why not just `else` instead of `else if`? Also, the comments seem to be outdated.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/index.tsx
> +  const path = useMemo(() => {
❓ Is this `useMemo` important to make the code work or is it an optimization?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/List.tsx
> +  path: {
💡 I think this could be a shared type.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +const getFieldMappingFingerprint = (
⚠️ I think this file has too many responsibilities and is a bit too long. For instance, this function could probably be extracted somewhere else, no? I've created a `src/domain/slice.ts` file to contain shared domain logic. Do you think it would be a good fit?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const primary: Record<string, string> = {};
💡 I know `@prismicio/types-internal` uses a lot of `Record`, but this type is actually false because there exists some `string` keys that don't have a corresponding `string` value, no? `Partial<Record<string, string>>` or `Map<string, string>` would better convey this.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const identicalSlices = useMemo<IdenticalSlice[]>(() => {
⚠️ Moving this code block into a `useIdenticalSlices` hook (in the same file or in another file) would make `ConvertLegacySliceModal` easier to read.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const [isModalOpen, setIsModalOpen] = useState<false | Type>(false);
💡 "Modal" isn't a good name for me, because it only describes a UX pattern where users can't click/interact outside of the element. Also, "isOpen" makes me think it's a boolean, but in fact you want to know which modal is open. Something like `const [dialog, setDialog] = useState<LegacySliceConversionType | undefined>()` would be clearer in my opinion (or maybe `ConvertLegacySliceDialogType` instead of `LegacySliceConversionType`).

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +    void (async () => {
💡 Is this IIFE necessary? It's not super easy to read in my opinion.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const {} = useSliceMachineActions();
⚠️ I don't understand why we call this hook as the return type isn't used.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +        console.error(
❓ Do we want to show a toast in case the operation doesn't work?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +      const customTypeSM = CustomTypes.toSM(customType);
❓ Does it work if called immediately after `refreshState(serverState)`?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.css.ts
> +export const form = style([
💡 You don't have to change your styles, but next time I would advice you to use `Box`. Inline with the Page Builder's team philosophy, we now want to:
1. Write new components with Storybook in `src/components` when they are specific to Slice Machine. Write them in the Editor's repository when they are sharable. 
2. Avoid writing styles with `@vanilla-extract/*` in domain code. Fallback to `Box` for contextual styles/layouts.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.css.ts
> +  sprinkles({
⚠️ No need to wrap `sprinkles` in `style`. You can directly call `sprinkles` (e.g., `export const form = sprinkles({ /* ... */ })`).

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts
> +export type ConvertLegacySliceModalProps = {
⚠️ For the sake of consistency, I think it's better to have props defined in the same file as the component using them. However, when props are shared, like your `FormProps`, I think it's fine to have them in a `types` file.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts
> +export type Type = (typeof types)[number];
⚠️ This is a too generic name 😊 What do you think of `LegacySliceConversionType` (or maybe `ConvertLegacySliceDialogType`)?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts
> +export type ConvertLegacySliceAndTrackArgs = {
⚠️ For the sake of consistency, in the front end we tend to define args and props close to the function or component using them.

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewSlice.tsx
> +export const FormAsNewSlice: React.FC<FormProps> = ({
💡 The uppermost component is a `Dialog` so I think `AsNewSliceDialog` would make more sense (or maybe `ConvertLegacySliceAsNewSliceDialog`). What do you think?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewSlice.tsx
> +            // Just a hack to trigger validation on init for better UX
❓ https://formik.org/docs/api/formik#validateonmount-boolean doesn't work?

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewSlice.tsx
> +                id="convert-legacy-slice-modal-as-new-slice"
⚠️ You can remove them if you haven't written Cypress/Vitest UI tests ^^

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewVariation.tsx
> +    errors.libraryID = "Does not exists.";
⚠️ Typo: "Does not exist." (without an "s").

2023-10-09 08:48 UTC, bapmrl commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewVariation.tsx
> +export const FormAsNewVariation: React.FC<FormProps> = ({
💡 Personally I think it's easier to read files when the most important export appears first ^^ I would move `FormAsNewVariation ` to the top and just follow "natural reading order" from top to bottom (I don't know if I'm clear).

2023-10-09 08:49 UTC, bapmrl reviewed
Excellent work 😍

Don't worry, I've added 40 comments and I know it's a lot... I don't want you to make a heart attack and a lot of them are just questions. I've tried to put priorities using the following icons: ⚠️, 💡 and ❓.

Let's have a call to quickly go through the comments if you want 😊

2023-10-09 09:14 UTC, lihbr commented on e2e-projects/next-upgrade/package.json
> +    "typescript": "5.1.6"
Aligned with what's on `slice-machine-ui`!

2023-10-09 09:15 UTC, lihbr commented on e2e-projects/next-upgrade/package.json
> +    "next": "13.4.17",
Updated

2023-10-09 09:15 UTC, lihbr commented on e2e-projects/next-upgrade/package.json
> +    "@types/node": "20.5.0",
It's what `npx create-next-app` created 🤷‍♀️

2023-10-09 09:17 UTC, lihbr commented on e2e-projects/next-upgrade/package.json
> +    "slicemachine": "start-slicemachine"
Yes!

2023-10-09 09:18 UTC, lihbr commented on e2e-projects/next-upgrade/package.json
> +    "@types/node": "20.5.0",
Reordered anyway

2023-10-09 09:19 UTC, lihbr commented on e2e-projects/next-upgrade/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
I removed it, but I all fairness I was just rolling with the defaults of `npx create-next-app` to avoid overthinking it

2023-10-09 09:20 UTC, lihbr commented on e2e-projects/next-upgrade/slicemachine.config.json
> +  "___repositoryName": "inspiring-briouat-syt67g",
Cleaned up

2023-10-09 09:22 UTC, lihbr commented on e2e-projects/next-upgrade/app/slice-simulator/page.tsx
> +import { components } from "../../slices";
Yes, there are no slices on this project by default, it's just a project legacy project after Slice Machine init :)

2023-10-09 09:28 UTC, lihbr commented on e2e-projects/next-upgrade/tsconfig.json
> +{
I guess it now wants one anyway, against, just plain default `npx create-next-app`

2023-10-09 09:29 UTC, lihbr commented on e2e-projects/next-upgrade/customtypes/kitchen_sink/index.json
> +{
All the slices in these custom types are legacy slices :)

2023-10-09 09:32 UTC, lihbr commented on packages/manager/src/managers/slices/SlicesManager.ts
> +			description: args.dest.variationName,
That's to align with what has been done so far: https://github.com/prismicio/slice-machine/blob/8a68d99c7dd7a00042998198e73f29bf5aea2767/packages/slice-machine/src/features/slices/actions/createSlice.ts#L49

Let me know about it

2023-10-09 09:33 UTC, lihbr commented on packages/manager/src/managers/slices/SlicesManager.ts
> +					legacyPaths: {
It's a new property introduced in `@prismicio/types-internal` to allow the backend to resolve composite and legacy slices to the correct model: https://www.notion.so/prismic/RFC-Introducing-legacyPaths-to-Shared-Slices-in-Prismic-to-streamline-transition-to-Slice-Machine-8ccf067c394f430d867b861cb084ed32

2023-10-09 09:38 UTC, lihbr commented on packages/manager/src/managers/slices/SlicesManager.ts
> +			}
There are 3 cases:
1. Convert to new shared slice
2. Convert to a new variation
3. Merge with an existing and identical variation

This if covers cases n°2 and n°3, the if `if (!maybeVariation)` covers n°2 (because if the target variation does not exist, then it means we're in case n°2)

I updated comments, let me know

2023-10-09 09:41 UTC, lihbr commented on packages/slice-machine/src/features/slices/sliceCards/NonSharedSliceViewCard.tsx
> +  path: {
Refactored!

2023-10-09 09:45 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/index.tsx
> +export { ConvertLegacySliceModal } from "./ConvertLegacySliceModal";
Moved it to `src/features/slices/modals/convertLegacySlice`, let me know if you prefer another location!

2023-10-09 09:50 UTC, lihbr commented on packages/slice-machine/src/features/slices/sliceCards/NonSharedSliceViewCard.tsx
> +      <ConvertLegacySliceModal slice={slice} path={path} />
Refactored!

2023-10-09 09:52 UTC, lihbr commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/index.tsx
> +      else if (typeof value.type === "string") {
Updated the comment and refactored to remove the unnecessary `else if`

2023-10-09 09:54 UTC, lihbr commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/index.tsx
> +  const path = useMemo(() => {
I guess it's just an optimization, I'm not familiar with how reactivity works in React, would the following also be reactive?

```tsx
const path = {
  customTypeID: customType.id,
  tabID: tabId,
  sliceZoneID: sliceZone?.key as string,
};
```

2023-10-09 09:55 UTC, lihbr commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/List.tsx
> +  path: {
Where could it be extracted in your opinion?

2023-10-09 09:55 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +const getFieldMappingFingerprint = (
Definitely!

2023-10-09 09:59 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const primary: Record<string, string> = {};
Type is always defined here, that's why we're using `?? ""` later on. Everything gets stringified before the function returns anyway to get a fingerprint, so it looks like it's pretty scoped here?

`Map` would be too overkill to deal with I think~

2023-10-09 10:03 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const identicalSlices = useMemo<IdenticalSlice[]>(() => {
I tried refactoring it, let me know if that reads better :)

2023-10-09 10:07 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const [isModalOpen, setIsModalOpen] = useState<false | Type>(false);
Refactored!

2023-10-09 10:08 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +    void (async () => {
Refactored, that was because the submit function couldn't be async

2023-10-09 10:10 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +  const {} = useSliceMachineActions();
Cleaned up 🙈

2023-10-09 10:13 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +        console.error(
Added a toast upon conversion error and updating the UI after 👌

2023-10-09 10:15 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +      const customTypeSM = CustomTypes.toSM(customType);
I switched them, good call!

2023-10-09 10:23 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.css.ts
> +export const form = style([
Ohhh, ok, now I get `Box`

Refactored what I could with it :)

2023-10-09 10:24 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.css.ts
> +  sprinkles({
Refactored!

2023-10-09 10:25 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts
> +export type Type = (typeof types)[number];
Yes! Refactored

2023-10-09 10:27 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts
> +export type ConvertLegacySliceModalProps = {
Refactored :)

2023-10-09 10:29 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/types.ts
> +export type ConvertLegacySliceAndTrackArgs = {
I agree, however, since it needs to be shared, I'm a bit clueless as of what's better to not have a circular dependency 🤔

2023-10-09 10:31 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewSlice.tsx
> +export const FormAsNewSlice: React.FC<FormProps> = ({
Refactored them all :)

2023-10-09 10:36 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewSlice.tsx
> +                id="convert-legacy-slice-modal-as-new-slice"
Removed!

2023-10-09 10:36 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewVariation.tsx
> +    errors.libraryID = "Does not exists.";
Fixed! 🙏

2023-10-09 10:38 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewVariation.tsx
> +export const FormAsNewVariation: React.FC<FormProps> = ({
I actually expect the main export to be last haha (since back in the days, we were doing `module.exports = { ... }` at the end of our JS files.

Let me know what would work best for you :)

2023-10-09 10:40 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewSlice.tsx
> +            // Just a hack to trigger validation on init for better UX
Ah, it does! Tried looking for it but didn't get to this page!

2023-10-09 14:02 UTC, lihbr commented on packages/slice-machine/lib/builders/CustomTypeBuilder/SliceZone/index.tsx
> +  const path = useMemo(() => {
Refactored!

2023-10-09 14:02 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/ConvertLegacySliceModal.tsx
> +      const customTypeSM = CustomTypes.toSM(customType);
Good as is

2023-10-09 14:02 UTC, lihbr commented on packages/slice-machine/components/Forms/ConvertLegacySliceModal/FormAsNewVariation.tsx
> +export const FormAsNewVariation: React.FC<FormProps> = ({
Refactored!

2023-10-10 07:29 UTC, bapmrl approved these changes
Excellent work Lucie!

I've just added 3 minor comments, that don't necessarily need to be addressed.

2023-10-10 07:29 UTC, bapmrl commented on packages/slice-machine/src/domain/slice.ts
> +  slice: LegacySlice | CompositeSlice | VariationSM,
💡 You could remove the `NonSharedSlice` type which is no longer used outside this module (or use it in your arg type) and for consistency, write a `function` instead of a `const`.

2023-10-10 07:29 UTC, bapmrl commented on packages/slice-machine/src/features/slices/convertLegacySlice/ConvertLegacySliceButton.tsx
> +export const ConvertLegacySliceButton: React.FC<
💡 For consistency, we don't use the `React` namespace and import each type/value manually (e.g., `import type { FC } from "react`).

2023-10-10 07:29 UTC, bapmrl commented on packages/slice-machine/src/features/slices/convertLegacySlice/ConvertLegacySliceButton.tsx
> +    slice.value.type === "Slice"
💡 I don't know if it's worth it and how we could name it, but that's the kind of domain function I would move to `packages/slice-machine/src/domain/slice.ts`.

2023-10-10 10:24 UTC, lihbr commented on packages/slice-machine/src/features/slices/convertLegacySlice/ConvertLegacySliceButton.tsx
> +    slice.value.type === "Slice"
I'm not really sure about one for now so I'll leave it as is 🤔

2023-10-10 12:06 UTC, bapmrl commented on packages/slice-machine/src/features/slices/convertLegacySlice/ConvertLegacySliceButton.tsx
> +    slice.value.type === "Slice"
Okay!

2023-10-11 08:01 UTC, bapmrl approved these changes

2023-10-11 08:01 UTC, merged