feat(slice-machine-ui): add Card component
prismicio/slice-machine pull request #1144
Opened 2023-09-22 17:04 UTC by bapmrl

Completes DT-1604.

2023-09-25 08:16 UTC, xrutayisire requested changes
First code only review, always nice work with you! 🙂

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/.storybook/preview.tsx
> -  argTypes: {
❓ What is the idea behind this change?
I see the diff on the stories but would like to understand the whole picture

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +      boxShadow: "0px 0px 0px 4px hsla(251, 63%, 63%, 0.1)",
⚠️ No box shadow from the system design, I guess? Is that normal that we don't have it?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +      [`${size.small} > &`]: { height: "180px" },
❓ When we will be using small or medium?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
⚠️ For me, we should avoid doing this, by talking to Benjamin it's just that he don't have the correct setup in Figma, and he is ok to do 32px here for example most of the time. Did you see that with him? Having to subtract the border feel strange for me 😕

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  img: [
❓ You don't want to all: unset for img?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +    { selectors: { "&:not([src])": { visibility: "hidden" } } },
⚠️ When this can happen? Should it not be a JavaScript condition for an error or something here?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  { marginBottom: `calc((${24 / 16}rem - ${16 / 16}rem) / 2)` },
❓ Where does this come from?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.tsx
> +    checked: _checked,
⚠️ Why extracting it with "_" to remove it from otherProps, while you would extract it normally and using it instead of doing `props.checked`. No?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.tsx
> +    variant = "solid",
❓I see that "solid" and "medium" are the default, how did you define it?

2023-09-25 08:16 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.tsx
> +  ...otherProps
❓ I'm always wondering, here you are typing the props with strictly 3 props. But you spread the rest. It should have no rest, at least it's not visible it's allowed. Should we extend the type to explain we accept some other HTML default props?

2023-09-25 09:41 UTC, bapmrl commented on packages/slice-machine/.storybook/preview.tsx
> -  argTypes: {
Before that change, all stories had (disabled) controls for `className` and `style`, even if the corresponding components didn't use these props. Now, `className` and `style` are hidden in all stories.

2023-09-25 09:46 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +      boxShadow: "0px 0px 0px 4px hsla(251, 63%, 63%, 0.1)",
I've checked and in [Prismic - Design System](https://www.figma.com/file/V5pub1BwPMJGY52YHmhTmX/Prismic---Design-System?mode=dev) I couldn't find an outline that is `4px` wide. I've only found `2px` (which exists in `@prismicio/editor-ui`) and `3px` (which doesn't exist in `@prismicio/editor-ui`). I'm not sure what to do. Maybe it's fine for now to keep it that way, as we only have one such outline.

2023-09-25 09:48 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +      [`${size.small} > &`]: { height: "180px" },
`small` and `outlined` will be used to select slices in the dialog to update the slice zone. `medium` and `solid` will be used everywhere else.

2023-09-25 10:00 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
For me, it's either:
1. @benjammartin configures Figma so that borders sit outside (instead of inside) components. It would then remove the need to make subtractions in the styles to match Figma.
2. @benjammartin keeps it the current way (so borders sit inside components in Figma), but we have to make subtractions.

Am I missing something?

2023-09-25 10:02 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +      boxShadow: "0px 0px 0px 4px hsla(251, 63%, 63%, 0.1)",
Ok, for me, we should just keep track with @benjammartin of this kind of things, so we know when to add it to the system design if needed.

2023-09-25 10:03 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
Good summary, If it's possible to change the configuration, I see only something simple. Much more to using sprinkles and all.

2023-09-25 10:06 UTC, benjammartin commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
Make subtractions. That's ok like this.

2023-09-25 10:06 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  img: [
Good question. It's not done by the CSS reset I inspired from when I decided to use `all: unset` (see https://github.com/elad2412/the-new-css-reset/blob/main/css/reset.css#L11)). It's probably not necessary for `img`, `video`... and may even break some browsers?

2023-09-25 10:08 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +    { selectors: { "&:not([src])": { visibility: "hidden" } } },
The default story doesn't specify a `src` and I didn't like how Chrome rendered the `img` in that case. I wanted to illustrate the component in it's "default"/"empty" state to highlight slots (where actual components can be passed).

2023-09-25 10:09 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
I personally don't like it, it means we cannot rely on the data from Figma directly, that we always have to think about it and that we cannot use sprinkles directly. Is it complicated to update the configuration?
For me, we will lose time over this during all SM life.

2023-09-25 10:13 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  img: [
Oh good to know! 
Interesting.

You should definitely create a Notion page with all your references, like System Design, Components libraries, this inspiration. You have so many good things to share in your head 😛

2023-09-25 10:14 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  { marginBottom: `calc((${24 / 16}rem - ${16 / 16}rem) / 2)` },
It comes from Figma, but I agree it's a bit obscure. Benjamin slightly offset the texts so that they appear to be vertically centered despite the `title` having a higher `lineHeight` than the `subtitle`.

Should I add a comment?

I would have preferred to have access to the `fontSize` and `lineHeight` in the theme, but they have been removed and I don't really have time to add them back.

2023-09-25 10:20 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.tsx
> +    checked: _checked,
1. I need access to the unspread `props` so that TypeScript can narrow down the type when `props.interactive` is `true`.
2. I don't want `checked`, `disabled`, `interactive` and `onClick` to be passed as is to the underlying `div`. These props help me derive other props, which are passed to the underlying `div` only when the `Card` is `interactive`.
3. I had to prefix `checked`, `disabled`, `interactive` and `onClick` with `_` otherwise ESLint would complain.

2023-09-25 10:20 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.tsx
> +    variant = "solid",
It's what will be most frequently used in the app.

2023-09-25 10:28 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  { marginBottom: `calc((${24 / 16}rem - ${16 / 16}rem) / 2)` },
Yeah no problem with the editor problem. A small comment could be nice for maintenance yes 🙌

2023-09-25 10:29 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.tsx
> +    checked: _checked,
Ok good one sorry, thanks for the explanation 🙂

2023-09-25 10:30 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.tsx
> +    variant = "solid",
The other comment made me understand thanks

2023-09-25 10:32 UTC, benjammartin commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
A quick explanation. Figma doesn't handle borders like a browser does.

Having an outside or inside border has no impact on the dimensions of a component in Figma. This is not the case when it's rendered in a browser.

This means that if we want to create an implementation that matches the Figma design exactly, we'll have to cheat in some way.

2023-09-25 10:34 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.tsx
> +  ...otherProps
I'm spreading the rest because consumers may pass `data-` attributes. Also, if the component where to be used as a Radix trigger, Radix would pass props which we wouldn't be aware of.

2023-09-25 10:39 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.css.ts
> +  img: [
That's true. The problem is always time ^^

2023-09-25 10:45 UTC, benjammartin commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
Edit : Except by turning the component in Autolayout.

2023-09-25 12:29 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.css.ts
> +        padding: calc.subtract(vars.space[32], vars.borderWidth[1]),
Ok Baptiste, I let you decide what you prefer in the meantime. We just need to react quickly after so we don't have too many things to change like the editor. 🙂

2023-09-25 12:38 UTC, xrutayisire approved these changes
LGTM, great work! 🙂

Last question, if we have in a slice zone, some Card with CardActions + CardFooter, and some only with CardFooter, is it ok that in terms of Design size (height) will be different?

2023-09-26 15:58 UTC, bapmrl commented
> LGTM, great work! 🙂
> 
> Last question, if we have in a slice zone, some Card with CardActions + CardFooter, and some only with CardFooter, is it ok that in terms of Design size (height) will be different?

I've fixed this issue ^^ It was an error on my side.

2023-10-04 08:14 UTC, xrutayisire commented on packages/slice-machine/src/components/Card/Card.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
Why these prettier-ignore and eslint-disable-next-line?

2023-10-04 08:48 UTC, bapmrl commented on packages/slice-machine/src/components/Card/Card.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
I'm removing those as discussed together ^^

2023-10-05 10:24 UTC, merged