feat(review): Satisfaction modal for advanced repository
prismicio/slice-machine pull request #1167
Opened 2023-10-12 07:58 UTC by xrutayisire

## Context

- Completes DT-1656

## The Solution

- Added a new manager call to get documents count
- Added a new shared hook to fetch documents count 
- Update review modal to use documents count to display or not the review modal
- Ensure the review modal has the correct display and tracking

## Impact / Dependencies

- Currently checking perf issue with the current work, if it's a problem or not

## Checklist before requesting a review
- [ ] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

2023-10-13 13:37 UTC, bapmrl requested changes
Very nice work! I just have some minor comments 😊

2023-10-13 13:37 UTC, bapmrl commented on packages/manager/src/managers/prismicRepository/types.ts
> +export type DocumentStatus = "published" | "draft";
⚠️ `DocumentStatus` doesn't appear to be used anywhere.

2023-10-13 13:37 UTC, bapmrl commented on packages/slice-machine/components/App/index.tsx
> +import { ReviewModal } from "@components/ReviewModal/ReviewModal";
💡 An `index` file could be added to avoid having `ReviewModal` twice in the import path.

2023-10-13 13:37 UTC, bapmrl commented on packages/slice-machine/src/modules/userContext/types.ts
> +export type UserReview = {
💡 I would expect to read both `UserReview` and `LegacyUserContextStoreType` below `UserContextStoreType`.

2023-10-13 13:37 UTC, bapmrl commented on packages/slice-machine/src/modules/userContext/index.ts
> +    onboarding: state.userContext.hasSendAReview ?? false,
❓ This makes me wonder whether a migration system should be introduced in the future. It would only make sense if we often find ourselves having to handle legacy data.

2023-10-13 13:37 UTC, bapmrl commented on packages/slice-machine/test/src/modules/userContext.test.ts
> +    it("should update user review onboaring to true when given USER_CONTEXT/SEND_REVIEW action", () => {
⚠️ Typo: `onboaring`.

2023-10-13 13:37 UTC, bapmrl commented on packages/slice-machine/components/ReviewModal/ReviewForm.tsx
> +  reviewType: keyof UserReview;
💡 There are multiple places where `keyof UserReview` is used. Maybe an additional `UserReviewType` would be useful? The original `UserReview` could be renamed to `UserReviewState` to differentiate the two.

2023-10-13 13:37 UTC, bapmrl commented on packages/slice-machine/components/ReviewModal/ReviewForm.tsx
> +                  placeholder="Tell me more..."
💡 I find this placeholder a bit weird ^^

2023-10-16 08:00 UTC, xrutayisire commented on packages/manager/src/managers/prismicRepository/types.ts
> +export type DocumentStatus = "published" | "draft";
Good one, removed document count management too quickly, my bad!

2023-10-16 08:02 UTC, xrutayisire commented on packages/slice-machine/src/modules/userContext/index.ts
> +    onboarding: state.userContext.hasSendAReview ?? false,
When we will remove local storage management from redux store, I think we should do this yes. It's mostly for that. 
To be sure not to forget a user can have an old value in the LS.

2023-10-16 08:02 UTC, xrutayisire commented on packages/slice-machine/components/ReviewModal/ReviewForm.tsx
> +                  placeholder="Tell me more..."
I will ask Sam 🙂
I can also put back the previous text. I followed Product specification but I agree before I felt it was ok.

2023-10-16 08:18 UTC, xrutayisire commented on packages/manager/src/managers/prismicRepository/types.ts
> +export type DocumentStatus = "published" | "draft";
Done, thanks 🙂
https://github.com/prismicio/slice-machine/compare/0a469566a9d6dbcf5cf401079af027ce402892c2..6c0b82ea256168917f9a18d43c7317ca8688b078

2023-10-16 08:18 UTC, xrutayisire commented on packages/slice-machine/components/App/index.tsx
> +import { ReviewModal } from "@components/ReviewModal/ReviewModal";
Done, thanks 🙂
https://github.com/prismicio/slice-machine/compare/0a469566a9d6dbcf5cf401079af027ce402892c2..6c0b82ea256168917f9a18d43c7317ca8688b078

2023-10-16 08:18 UTC, xrutayisire commented on packages/slice-machine/src/modules/userContext/types.ts
> +export type UserReview = {
Done, thanks 🙂
https://github.com/prismicio/slice-machine/compare/0a469566a9d6dbcf5cf401079af027ce402892c2..6c0b82ea256168917f9a18d43c7317ca8688b078

2023-10-16 08:18 UTC, xrutayisire commented on packages/slice-machine/test/src/modules/userContext.test.ts
> +    it("should update user review onboaring to true when given USER_CONTEXT/SEND_REVIEW action", () => {
Done, thanks 🙂
https://github.com/prismicio/slice-machine/compare/0a469566a9d6dbcf5cf401079af027ce402892c2..6c0b82ea256168917f9a18d43c7317ca8688b078

2023-10-16 08:18 UTC, xrutayisire commented on packages/slice-machine/components/ReviewModal/ReviewForm.tsx
> +  reviewType: keyof UserReview;
Done, thanks 🙂
https://github.com/prismicio/slice-machine/compare/0a469566a9d6dbcf5cf401079af027ce402892c2..6c0b82ea256168917f9a18d43c7317ca8688b078

2023-10-16 10:08 UTC, bapmrl approved these changes

2023-10-16 10:21 UTC, merged