feat(slice-machine-ui): update List component
prismicio/slice-machine pull request #1174
Opened 2023-10-18 08:16 UTC by bapmrl

Completes DT-1679 and DT-1680.

2023-10-18 15:46 UTC, xrutayisire requested changes
Super work! Really nice to see a simplification of the overall codebase 🤩
One small comment that I think we should add.

2023-10-18 15:46 UTC, xrutayisire commented on packages/slice-machine/src/components/Window/Window.css.ts
> +  {},
⚠️ We should add a comment here, since it's hard to understand that first this is made to let the possibility to use root as a selector. And second used in other style files, but not in this one.
I don't really like having to do this, actually it creates a hard to maintain dependency but I don't have a better solution 👀.
I would recommend having a comment here to explain where it's used or at least it's used elsewhere ^^

2023-10-19 10:23 UTC, bapmrl commented on packages/slice-machine/src/components/Window/Window.css.ts
> +  {},
I've added a comment as discussed together 😊

2023-10-19 10:27 UTC, xrutayisire approved these changes
All good! ✅

2023-10-19 10:29 UTC, merged