ffix(repository name): Repository name length can be up to 63 and not only 30 characters
prismicio/slice-machine pull request #1175
Opened 2023-10-19 08:14 UTC by xrutayisire

## Context

- Completes DT-1688

## The Solution

- Created constant in order to save the correct min max repository name length

## Impact / Dependencies

- Prevent user to have an error after creating a valid repository name in wroom

## Checklist before requesting a review
- [x] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

2023-10-19 10:44 UTC, bapmrl requested changes

2023-10-19 10:44 UTC, bapmrl commented on packages/init/src/constants.ts
> +export const REPOSITORY_NAME_VALIDATION = {
❓ Why not import it from the manager instead of defining it twice? It would prevent issues where we update one package, but not the other.

2023-10-19 10:44 UTC, bapmrl commented on packages/manager/src/constants/REPOSITORY.ts
> +export const REPOSITORY_NAME_VALIDATION = {
💡 I would name the file `REPOSITORY_NAME_VALIDATION` as other constants seem to be named very "precisely".

2023-10-19 10:44 UTC, bapmrl commented on packages/manager/src/constants/REPOSITORY.ts
> +	min: 4,
💡 It seems other constants which expose values in an object, have these values either `UpperCamelCased` or `UPPER_SNAKE_CASED`.

2023-10-19 10:44 UTC, bapmrl commented on packages/init/src/SliceMachineInitProcess.ts
>  				const minRule = validation.LessThan4
⚠️ There's something confusing here. Why is `LessThan4` explicitly stating `4` while we use the word `min` in `REPOSITORY_NAME_VALIDATION`? Same thing for `MoreThan30`.

2023-10-19 10:48 UTC, xrutayisire commented on packages/init/src/constants.ts
> +export const REPOSITORY_NAME_VALIDATION = {
That's a good question I asked myself, can I just reuse a constant from the manager. It has not been done yet, @lihbr maybe, WDYT?

2023-10-19 10:48 UTC, xrutayisire commented on packages/manager/src/constants/REPOSITORY.ts
> +	min: 4,
I will check to be more aligned, you're right

2023-10-19 10:49 UTC, xrutayisire commented on packages/init/src/SliceMachineInitProcess.ts
>  				const minRule = validation.LessThan4
Sorry, I forgot to update these naming here, I don't want to have this stored directly in the code but only in the constant now 🙂

2023-10-19 10:54 UTC, lihbr commented on packages/init/src/SliceMachineInitProcess.ts
>  				const minRule = validation.LessThan4
Yes, let's find a more generic name

2023-10-19 10:55 UTC, lihbr commented on packages/init/src/constants.ts
> +export const REPOSITORY_NAME_VALIDATION = {
Indeed, this whole "repository name validation/generation" module quite deserve a unique place to exists, maybe it makes more send to move it as methods of the repository manager(?)

2023-10-19 11:18 UTC, xrutayisire commented on packages/init/src/constants.ts
> +export const REPOSITORY_NAME_VALIDATION = {
I feel like it's a bit annoying having to call the manager and passing it every place needed just to get the constant, no? Or maybe that's only what we want to do?

2023-10-19 13:35 UTC, lihbr commented on packages/init/src/constants.ts
> +export const REPOSITORY_NAME_VALIDATION = {
No for constants I agree, imports are enough.

I was thinking about all the helpers to validate repository names & such.

2023-10-19 14:34 UTC, xrutayisire commented on packages/init/src/constants.ts
> +export const REPOSITORY_NAME_VALIDATION = {
Done 🙂

2023-10-19 14:34 UTC, xrutayisire commented on packages/manager/src/constants/REPOSITORY.ts
> +export const REPOSITORY_NAME_VALIDATION = {
Done 🙂

2023-10-19 14:34 UTC, xrutayisire commented on packages/manager/src/constants/REPOSITORY.ts
> +	min: 4,
Done 🙂

2023-10-19 14:34 UTC, xrutayisire commented on packages/init/src/SliceMachineInitProcess.ts
>  				const minRule = validation.LessThan4
Done 🙂

2023-10-19 17:04 UTC, bapmrl commented on packages/init/src/SliceMachineInitProcess.ts
>  				const minRule = validation.LessThan4
I still see `LessThan4` and `MoreThan30` ^^

2023-10-19 17:06 UTC, xrutayisire commented on packages/init/src/SliceMachineInitProcess.ts
>  				const minRule = validation.LessThan4
I forgot to push my whole fix commit haha thanks

2023-10-20 08:57 UTC, bapmrl approved these changes

2023-10-20 08:57 UTC, bapmrl commented on packages/init/src/lib/repositoryDomain.ts
> +	Min: "Min",
💡 `LessThanMin` and `MoreThanMax` would be clearer ^^

2023-10-20 14:37 UTC, xrutayisire commented on packages/init/src/lib/repositoryDomain.ts
> +	Min: "Min",
Done thanks

2023-10-20 14:47 UTC, merged