chore: add new workflow to publish-stable
prismicio/slice-machine pull request #1261
Opened 2024-01-10 11:17 UTC by michelchau

## Context

[DT-1773](https://linear.app/prismic/issue/DT-1773/add-a-manually-triggered-github-workflow-to-publish-stable-versions)

## The Solution

## Impact / Dependencies

## Checklist before requesting a review
- [ ] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

## [OPT] Preview

2024-01-10 13:57 UTC, bapmrl requested changes
Excellent!

I've added some comments though. Tell me if you prefer to address them asynchronously or if you'd like us to call 😊

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +          slicemachine/adapter-next:
💡 Would it be possible to have a direct match with the workspaces names? In this case, it would be `@slicemachine/adapter-next`. That way, the input names would use the `@` scopes consistently.

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +            default: 'None'
💡 I've thought about it and I think `decline` would be a better name than `None` as it's also used by [Yarn](https://yarnpkg.com/cli/version).

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +            options:
💡 Would it be possible to have the options appear in the following order: `major`, `minor`, `patch` and finally `decline`? It would be more intuitive as SemVer follows the same `<major>.<minor>.<patch>` order.

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +          slicemachine/init:
⚠️ You forgot `@slicemachine/adapter-sveltekit` between `@slicemachine/adapter-nuxt2` and `@slicemachine/init`.

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +            description: slicemachine/adapter-next
❓ Does the `description` correspond to the name of the input displayed in GitHub's popover?

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +        with:
💡 I'm not sure we need the `fetch-depth` and `ref` options, at least probably not the `ref` option as this workflow will only run on the `main` branch.

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
💡 Is there a GitHub option to only allow this workflow to run on the `main` branch?

⚠️ What about security? For now, we don't want contributors outside Prismic to be able to publish releases via this workflow.

⚠️ Could you please format the file with Prettier? If you don't have it configured in your editor, then the [online playground](https://prettier.io/playground) should give a similar result.

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +          package=$(echo '${{ toJSON(github.event.inputs) }}' | jq -c)
💡 If I understand well those lines, you could use the following names instead to be consistent with the `publish` script:
- `package` → `inputs`.
- `keys` → `package_names`.
- `package_output` → `specifiers`.
- `value` → `package_release_type`.

2024-01-10 13:57 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +            package_output+="@$key:$value "
⚠️ I'm not sure it's the case, but I think you are including the `decline`d values when you should not ^^ Indeed, the `script` expects only the packages to be published. The other packages should be filtered out.

2024-01-10 16:17 UTC, michelchau commented on .github/workflows/publish-stable.yml
> +          slicemachine/adapter-next:
We can't use @ on the inputs variable.

2024-01-10 16:50 UTC, michelchau commented on .github/workflows/publish-stable.yml
I added some condition for main branch only.

2024-01-11 09:21 UTC, bapmrl reviewed
Excellent job! I've just added 4 small questions and we'll be good.

2024-01-11 09:21 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +    if: 'startsWith(github.ref, ''refs/heads/main'')'
❓ Why use `'` twice? Also, I've noticed in the `publish-unstable` workflow we used `${{ }}` around the whole expression (instead of a single `'`). Which option is better?

2024-01-11 09:21 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +            if
❓Is it normal to have 2 `if`s in a row?

2024-01-11 09:21 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +            if ["$package_name == slicemachine/*" && "package_release_type" != "decline"]; then
❓ I can't find a `package_name` variable. Should the `package` variable in the `for` loop be renamed to `package_name`?

2024-01-11 09:21 UTC, bapmrl commented on .github/workflows/publish-stable.yml
> +          SENTRY_AUTH_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN }}'
❓ Why add extra single quotes `'` around the `${{`? We didn't do that in the `publish-unstable` workflow.

2024-01-11 10:21 UTC, merged