docs: add public Git error messages
prismicio/slice-machine pull request #1283
Opened 2024-02-01 21:57 UTC by angeloashmore

## Context

DT-1941

## The Solution

Add Markdown files for each Git-specific error. We will link to the public GitHub pages to allow users to learn more about an error.

We can use the `prismic.dev/msg` domain to alias links:

```
https://prismic.dev/msg/slicemachine/main/git-error.md
```

In the future, we may move these error messages to a https://prismic.io-hosted page.

## Impact / Dependencies

The GitHub integration must link to the correct page.

## Checklist before requesting a review

- [x] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [x] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

2024-02-05 16:41 UTC, bapmrl requested changes
Excellent!

2024-02-05 16:41 UTC, bapmrl commented on messages/git-error.md
> +An error occured while syncing models to Prismic from a Git repository.
⚠️ Typo: "occurred".

2024-02-05 16:41 UTC, bapmrl commented on messages/git-error.md
> +Syncing the project again by committing to the repository.
💡 Maybe "Sync" would be better?

2024-02-05 16:41 UTC, bapmrl commented on messages/git-invalid-slice-machine-config.md
> +- Invalid JSON with incorrect syntax
⚠️ Missing "." at the end.

2024-02-05 16:41 UTC, bapmrl commented on messages/git-unauthorized-github.md
> +# Git: Unauthorized Github access
⚠️ Typo: "GitHub".

2024-02-05 16:41 UTC, bapmrl commented on messages/git-unauthorized-prismic.md
> +# Git: Unauthorzed Prismic access
⚠️ Typo: "Unauthorized".

2024-02-05 16:41 UTC, bapmrl commented on messages/git-unauthorized-prismic.md
> +First, ensure a Prismic Write API token was saved in Slice Machine. You can set, update, and delete a Write API token from Slice Machine's Settings page.
⚠️ This sentence isn't 100% exact as the token is only asked in the `GitRepositoryConnectDialog` when connecting to a repository. The user needs to disconnect the repository in order to be able to update the token (when connecting again).

2024-02-05 16:41 UTC, bapmrl commented on messages/git-unsupported-adapter.md
> +- [`@slicemachine/adapter-next`](https://github.com/prismicio/slice-machine/tree/main/packages/adapter-next#readme): Next.js projects
❓ In a previous file you used `.` at the end of list items. What style should be adopted (for the sake of consistency)?

2024-02-05 23:32 UTC, angeloashmore commented on messages/git-unauthorized-prismic.md
> +First, ensure a Prismic Write API token was saved in Slice Machine. You can set, update, and delete a Write API token from Slice Machine's Settings page.
Thanks, I updated it to these instructions:

```md
## How to fix the issue

Re-connect the Prismic and GitHub repositories, ensuring the Write API token is active and correct:

1. In Slice Machine's Settings page, disconnect the connected GitHub repository.
1. Re-connect the GitHub repository.
1. When asked for a Write API token, provide a valid token.

Tokens can be created following these steps:

1. In the Prismic repository, navigate to the Settings page.
1. Select **API & Security** in the sidebar and the **Write APIs** tab at the top of the page.
1. Create and copy a new Write API token or copy an existing token.
```

2024-02-05 23:42 UTC, angeloashmore commented on messages/git-unsupported-adapter.md
> +- [`@slicemachine/adapter-next`](https://github.com/prismicio/slice-machine/tree/main/packages/adapter-next#readme): Next.js projects
Thanks, I added periods to each item.

In general, I follow this pattern:

- If list items are sentences, use periods.
- If list items only contain specific subjects, don't use periods.

With periods:

> Follow these guidelines:
> - Use apples liberally.
> - Avoid bananas when possible.
> - Puree carrots and use for something else.

Without periods:

> The following fruits may be used:
> - Apple
> - Banana
> - Carrot

2024-02-06 08:16 UTC, bapmrl approved these changes

2024-02-06 18:33 UTC, merged