feat(slice-machine): disable push changes with connected Git repo
prismicio/slice-machine pull request #1298
Opened 2024-02-19 16:58 UTC by bapmrl

Completes DT-1901.

2024-02-20 20:54 UTC, angeloashmore requested changes
It works well! I added a wording suggestion, which I will let you and @benjammartin decide.

It looks like E2E tests are broken as of this change, however. Do you have an idea on how to fix it?

2024-02-20 20:54 UTC, angeloashmore commented on packages/slice-machine/src/features/changes/PushChangesButton.tsx
> +      content="This repository has been set up to use the Git workflow."
Is there room to add an extra bit of information?

> This project uses the Git workflow. Push your changes to ${provider} to update Prismic.

`${provider}` would be "GitHub," "GitLab," etc.

2024-02-22 16:41 UTC, bapmrl commented on packages/slice-machine/src/features/changes/PushChangesButton.tsx
> +      content="This repository has been set up to use the Git workflow."
I've made the change @angeloashmore 😊

2024-02-23 02:43 UTC, angeloashmore approved these changes
Looks good!

2024-02-23 09:35 UTC, bapmrl commented
Thanks @angeloashmore!

2024-02-28 11:08 UTC, merged