improvement(sideNav): increase css mobile breakpoint
prismicio/slice-machine pull request #1346
Opened 2024-04-22 15:06 UTC by levimykel

## Context
[DT-2112](https://linear.app/prismic/issue/DT-2112)

Increases the mobile side navigation breakpoint from `small` to `medium`.

## The Solution
- Increase the breakpoint in CSS files from `767px` to `1011px`
- Update side nav components to include the medium breakpoint when using `useMediaQuery`

## Impact / Dependencies
- None

2024-04-23 08:12 UTC, bapmrl requested changes
Nice first PR on your first day in the team 👍

I just have 2 questions (❓) and 1 suggestion (💡).

1. ❓ Did you check it works in both the app and Storybook?
2. ❓ Have you shared a proposal on the `#page-builder-dev` channel to improve the API for using and composing breakpoints?

2024-04-23 08:12 UTC, bapmrl commented on packages/slice-machine/components/Navigation/ChangesItem.tsx
> +  isMedium = isMedium || isSmall;
💡 Sorry, I've thought about it, and I think your `const isBreakpoint = isSmall || isMedium` was clearer 🙂 It uses a `const` instead of a `let` and it doesn't mutate an already assigned variable.

2024-04-26 13:08 UTC, bapmrl requested changes
Nearly there 🙂

2024-04-26 13:08 UTC, bapmrl commented on packages/slice-machine/src/components/SideNav/SideNav.tsx
> +  const isMedium = useMediaQuery({ max: "medium" });
💡 I think just `const visible` would make more sense, because `isMedium` doesn't really reflect what `{ max: "medium" }` means. Indeed, `{ max: "medium" }` matches both the `small` and `medium` breakpoints.

2024-04-26 13:08 UTC, bapmrl commented on packages/slice-machine/src/components/SideNav/SideNavEnvironmentSelector.tsx
> +  const isMedium = useMediaQuery({ max: "medium" });
💡 Same comment. Maybe `const collapsed` would make more sense?

2024-04-26 13:08 UTC, bapmrl commented on packages/slice-machine/src/legacy/components/Navigation/ChangesItem.tsx
> +  const isMedium = useMediaQuery({ max: "medium" });
💡 Same comment. Maybe `const collapsed` would make more sense?

2024-04-26 13:30 UTC, levimykel commented on packages/slice-machine/src/components/SideNav/SideNav.tsx
> +  const isMedium = useMediaQuery({ max: "medium" });
Yeah, I agree that this is better.

2024-04-26 13:33 UTC, bapmrl approved these changes
Excellent!

2024-04-26 13:43 UTC, merged