[V0.1.1] Implement slicemachine-core & sm-init packages.
prismicio/slice-machine pull request #186
Opened 2021-10-05 10:30 UTC by Heyrows

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-10-08 07:54 UTC, Miniplop reviewed
Good job @Heyrows 👍 

Can you add the new line at the end of every new file plz  ? I think prettier can get ride of them easily.

2021-10-08 07:54 UTC, Miniplop commented on packages/slicemachine-core/src/utils/files.ts
> +  readJson(pathToFile: string): Record<string, unknown> {
Why we have a safe and a not safe read method, we want only to use the safe one right ?

2021-10-08 10:01 UTC, MarcMcIntosh reviewed
Defiantly needs unit tests

2021-10-08 10:01 UTC, MarcMcIntosh commented on package.json
> +    "**/packages/slice-machine/**/*.@(js|jsx|ts|tsx|)": "yarn --cwd ./packages/slice-machine eslint && yarn --cwd ./packages/slicemachine-core eslint && yarn --cwd ./packages/sm-init eslint",
`**/packages/slice-machine/**/*.@(js|jsx|ts|tsx|)` will only run when files in the slice-machine package have been modified.

That's not what we want. I've fixed this in the ls-repos branch, but should be fixed here to

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/auth.ts
> +  if (confirmation === 'q') return process.exit(-1);
we can support ctrl+c
`confirmation === 'q' || confirmation === '\u0003'`

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/communication.ts
> +  return // fetch and set cookie
fixed in another pr

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/communication.ts
> +  return // fetch
fixed in another pr

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/communication.ts
> +  return url
fixed in another PR

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/utils/framework.ts
> +  Framework.svelte
remember there is a gatsby PR that modifies this

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/sm-init/package.json
> +    "slicemachine-core": "link:../slicemachine-core"
fixed in another PR

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +  await core.Auth.login();
can't login to a different base?

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/validate-pkg.ts
> +    return process.exit(-1);
why a minus number?

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function createDefaultAuthConfig(cwd?: string): AuthConfig {
not a good name for the param.
cwd = current working directory.
the `.prismic` config is kept in the users home directory.

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function getOrCreateAuthConfig(cwd?: string): AuthConfig {
same as above

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function updateAuthConfig(data: Partial<AuthConfig>, cwd?: string): void {
same as above

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function removeAuthConfig(cwd?: string): void {
same as above

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function setAuthConfigCookies(base: string, cookies: ReadonlyArray<string> = [], cwd?: string): void {
same as above

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/utils/files.ts
> +    return JSON.parse(this.readString(pathToFile)) as Record<string, unknown>;
What if it's an array?

2021-10-08 10:01 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/utils/files.ts
> +  readFirstOf<V, O extends { [key: string]: unknown }>(
What's this for?

2021-10-11 08:21 UTC, Heyrows commented on packages/slicemachine-core/src/utils/files.ts
> +  readJson(pathToFile: string): Record<string, unknown> {
I think that sometimes you want to fail in order to send a custom error.

2021-10-11 08:29 UTC, Heyrows commented on packages/slicemachine-core/src/utils/framework.ts
> +  Framework.svelte
I guess until the Core is actually being used, there is no need to worry about it

2021-10-11 08:31 UTC, Heyrows commented on packages/sm-init/src/index.ts
> +  await core.Auth.login();
You can if you change the base at core initialization

2021-10-11 08:58 UTC, arnaudlewis commented on packages/slicemachine-core/src/utils/files.ts
> +  readFirstOf<V, O extends { [key: string]: unknown }>(
Sounds familiar haha! It read the first file it can find based on an array of paths you provide.
We use it for instance when we want to read mocks.
Either it finds custom mocks and read it or simply try to read the next path, the generated mocks ;)

2021-10-11 09:04 UTC, Heyrows commented on packages/sm-init/src/index.ts
> +  await core.Auth.login();
Done, allowed people to pass flags such as "--base" and "--cwd" for now

2021-10-11 09:10 UTC, arnaudlewis commented on packages/slicemachine-core/src/core/index.ts
> +    get: (apiEndpoint: string, token: string, sliceId: string) => Promise<any>,
why any everywhere?

2021-10-11 09:11 UTC, Heyrows commented on packages/slicemachine-core/src/utils/files.ts
> +    return JSON.parse(this.readString(pathToFile)) as Record<string, unknown>;
That's a good remark, I actually used a record to avoid having an any

2021-10-11 09:12 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
> +    get: (apiEndpoint: string, token: string, sliceId: string) => Promise<any>,
Because the types are not implemented yet.

2021-10-11 09:13 UTC, arnaudlewis commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function createDefaultAuthConfig(cwd?: string): AuthConfig {
You're right on this one it should be home directory
But in the Path module it's initialised by default with the home directory so maybe we shouldn't be able to change that for now

2021-10-11 09:19 UTC, arnaudlewis commented on packages/slicemachine-core/src/utils/files.ts
> +    return JSON.parse(this.readString(pathToFile)) as Record<string, unknown>;
I guess it simply shouldn't be or if that makes sense we'll add a function for it :)
But by default you wanna read a path

2021-10-11 09:22 UTC, Heyrows commented on packages/slicemachine-core/src/core/auth.ts
> +  if (confirmation === 'q') return process.exit(-1);
done

2021-10-11 09:25 UTC, MarcMcIntosh commented
Theres a biug with `core.Auth.login` the event listeners aren't removed, and it causes bugs to happen in later stages

```
  await core.Auth.login(); // something is wrong here.
  process.stdin.removeAllListeners() // this fixes it
  ```

2021-10-11 09:25 UTC, arnaudlewis commented on packages/slicemachine-core/src/utils/framework.ts
> +  Framework.svelte
None shouldn't be part of it I guess idk.
And for the list it should be : `Object.values(Framework)`
It's better than updating the list manually.
If none remains you can filter it, so the framework enum will always be in sync with SupportedFramework

2021-10-11 10:06 UTC, arnaudlewis commented on packages/slicemachine-core/src/core/index.ts
> +    get: (apiEndpoint: string, token: string, sliceId: string) => Promise<any>,
do we plan on doing so before the release?

2021-10-11 10:09 UTC, arnaudlewis commented
> Theres a biug with `core.Auth.login` the event listeners aren't removed, and it causes bugs to happen in later stages
> 
> ```
>   await core.Auth.login(); // something is wrong here.
>   process.stdin.removeAllListeners() // this fixes it
> ```

Maybe we should have a callback system but if the login function doesn't remove it's own listeners, it's really error prone and anyone using it elsewhere could easily forget to add an extra line to removeAllListeners

2021-10-11 10:41 UTC, Heyrows commented
> Theres a biug with `core.Auth.login` the event listeners aren't removed, and it causes bugs to happen in later stages
> 
> ```
>   await core.Auth.login(); // something is wrong here.
>   process.stdin.removeAllListeners() // this fixes it
> ```

The code now remove it's own listener, I just forgot to do it in the first place.

2021-10-12 07:50 UTC, Miniplop approved these changes
Nice :)

2021-10-12 07:50 UTC, Miniplop commented on packages/slicemachine-core/jest.config.js
> +/*
I think you can remove all the commented lines in this file

2021-10-12 08:51 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
> +    get: (apiEndpoint: string, token: string, sliceId: string) => Promise<any>,
I think hugo did on his branch

2021-10-12 13:35 UTC, MarcMcIntosh reviewed
I'm seeing lots of files and functions with out tests :/

2021-10-12 13:35 UTC, MarcMcIntosh commented on packages/slicemachine-core/__tests__/src/core/auth.test.ts
> +describe("communication", () => {
should be auth?

2021-10-12 13:36 UTC, MarcMcIntosh requested changes
Would be a good idea to add them now before branches start getting merged so we know what breaks/changes when they are merged

2021-10-14 15:25 UTC, MarcMcIntosh approved these changes

2021-10-14 15:25 UTC, merged