Ls repos
prismicio/slice-machine pull request #188
Opened 2021-10-07 15:08 UTC by MarcMcIntosh

Added a method to get the repo names :)

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-10-12 12:41 UTC, Miniplop commented on packages/sm-init/src/index.ts
> +  const repoName = await maybeExistingRepo(config.cookies, config.base);
why we don't use the base constant previously set ? And I think the FileSystem.getOrCreateAuthConfig(); can be put inside the fonction, seems to me that we always want to get the cookie from the authConfig right ?

2021-10-12 12:41 UTC, Miniplop commented on packages/sm-init/src/steps/index.ts
> +export { maybeExistingRepo } from './maybe-existing-repo'
new line here, prettier don't catch this ?

2021-10-12 12:41 UTC, Miniplop commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +}
no new line here

2021-10-12 12:41 UTC, Miniplop commented on packages/slicemachine-core/index.ts
> +export * from './src/core'
nice 😊

2021-10-12 12:41 UTC, Miniplop commented on packages/slicemachine-core/src/core/auth.ts
> +      resolve(); // todo add cookies here
I don't see the goal of creating a promise to return cookies if the promise don't return the cookies.

2021-10-12 12:41 UTC, Miniplop commented on .github/workflows/test.yml
> -          cache: "yarn"
I think we can keep the cache in CI. The problem in the CI is already solved :)

2021-10-12 12:47 UTC, Heyrows commented on packages/sm-init/README.md
> +- then `pushd packages/slicemachine-core && yarn build && popd && pushd packages/sm-init && yarn build && popd`
what's pushd ?

2021-10-12 12:47 UTC, Heyrows commented on packages/sm-init/package.json
> +    "chalk": "^4.1.2",
We already have Chalk and Ora on the Core side because the login requires it, do you think we need it here or we could export some helpers ?
Not saying one is better than the other but I don't think it's a good idea to have on both sides.

2021-10-12 12:51 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/auth.ts
> +      resolve(); // todo add cookies here
the cookies are needed in a few places, but i guess they can be read form disk

2021-10-12 12:54 UTC, MarcMcIntosh commented on packages/sm-init/README.md
> +- then `pushd packages/slicemachine-core && yarn build && popd && pushd packages/sm-init && yarn build && popd`
like cd but will work on windows too :)
https://en.wikipedia.org/wiki/Pushd_and_popd

2021-10-12 12:56 UTC, MarcMcIntosh commented on packages/sm-init/package.json
> +    "chalk": "^4.1.2",
I think libraries like chalk and ora and make for cli's like the init script, rather than have them in the core it's self?

2021-10-12 13:54 UTC, Miniplop commented on packages/slicemachine-core/src/core/auth.ts
> +      resolve(); // todo add cookies here
My point was for now the resolve don't return nothing `resolve();` so what the purpose of using promise here instead of regular fonction ?

2021-10-12 15:56 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/auth.ts
> +      resolve(); // todo add cookies here
so we can await later on

2021-10-12 16:10 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +  const repoName = await maybeExistingRepo(config.cookies, config.base);
can do i guess

2021-10-12 16:12 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +  const repoName = await maybeExistingRepo(config.cookies, config.base);
Although, this may cause issues if some-one logs in using the `prismic-cli` the runs sm init :/

2021-10-12 16:13 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/index.ts
> +export { maybeExistingRepo } from './maybe-existing-repo'
re-ran prettier, gitup doesn't use git-hooks (yet)

2021-10-12 16:14 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +  const repoName = await maybeExistingRepo(config.cookies, config.base);
yes a few functions, the create repo function will also need that cookie

2021-10-12 16:17 UTC, MarcMcIntosh commented on packages/sm-init/package.json
> +    "chalk": "^4.1.2",
ora isn't used in the sm-api anymore

2021-10-13 08:03 UTC, Miniplop commented on packages/sm-init/src/steps/index.ts
> +export { maybeExistingRepo } from './maybe-existing-repo'
That's a problem, you put the pre-commit hook to catch those errors and avoid code style inconsistencies. So how can you ensure that your code respect our standard ?

2021-10-14 12:23 UTC, Miniplop approved these changes
LGTM 💪

2021-10-18 09:09 UTC, Heyrows commented on packages/sm-init/package.json
> +    "chalk": "^4.1.2",
The only use in the Core is the login function that make it works in both the CLI and the init. I don't know if it's a good thing to remove it since the style is the same between CLi and Init.
Don't really know what to do here tbh 🤷‍♂️

2021-10-18 10:41 UTC, Heyrows requested changes

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/.eslintrc.json
> +  "ignorePatterns": ["build", "templates", "**/__tests__/**"]
I know it doesn't come from you but I don't think tests should be excluded.
It's important to right clear tests, it's part of the code.
To debate ^^

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        "foo-repo": { dbid: "abcd", role: "OWNER" },
incoherence with the lines below.
`OWNER` is not a valid value here, `Owner` is.
This is something that would have been caught by the linter and i'm surprised typescript didn't warn about it.
It's always preferable to use an Enum, that way if the value change you have to change it at one place only.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +    nock("https://auth.prismic.io")
Just a suggestion, but could it be better to use another value than prismic.io, just so we can detect any hard coded prismic.io we might have ?

It's just a suggestion, i didn't applied it myself yet.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        "foo-repo": { dbid: "abcd", role: "OWNER" },
I would use the enum here. And maybe define that at the top level of all tests since they seem to all use the same.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +      const fn = () => communication.validateRepositoryName();
I think the function (with typescript) should validate a value, the value should always be defined.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +      const repoName = Array.from({ length: 31 }, () => "a").join("");
funny, creative 😂

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        "Must have four or more alphanumeric characters and/or hyphens."
All these errors are really very precise.
If we decide to change one of them the test would fail automatically.
I think an enum would be good for this. More robust.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        .get(`/app/dashboard/repositories/${repoName}/exists`)
We have an endpoint modules in the Core and I think these should be inside of it.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        .get(`/app/dashboard/repositories/${repoName}/exists`)
same

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        .get(`/app/dashboard/repositories/${repoName}/exists`)
same

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        communication.validateRepositoryName(repoName, "https://example.com")
should this function be in the core also ?

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +        communication.validateRepositoryName(repoName, "https://example.com")
which doesn't mean it require more test because it would just call the one you made.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +      const repositories = maybeParseRepoData(res.data.repositories);
good things to have extracted it in a function but I think that the case where `data.repositories` doesn't exist should be handled here.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +  if (typeof repos === "string") return JSON.parse(repos) as RepoData;
You should use IO-TS because here if the contract change you wouldn't find it out until it breaks somewhere.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
> +    list: (token: string, base?: string) => Promise<Communication.RepoData>;
If it's inside the core, you don't need the base as parameter, the Core will provide :)

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
> +    validateName: (
same

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
> +    list: (token: string, base?: string) => Promise<Communication.RepoData>;
I wonder if we need the token also or can it come from the Filesystem directly

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
> +      ) => Communication.validateRepositoryName(name, base, existingRepo),
return type is missing.

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/utils/cookie.ts
> +export function serialize(
lots of prettier stuff, it's weird that it was triggered in your branch but not before, did you make a changes to the prettier conf ?

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/.eslintrc.json
> +  "ignorePatterns": ["build", "templates", "**/__tests__/**"]
same as the other eslint file

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/utils/poll.ts
> +    resolve: (value: void | PromiseLike<void>) => void,
how can value be a void ?

2021-10-18 10:41 UTC, Heyrows commented on packages/slicemachine-core/src/utils/poll.ts
> +    resolve: (value: void | PromiseLike<void>) => void,
I think the code before was clearer and it returned the result as well, i'm not sure why you changed it like this.
The arguments were a lot clearer and the Result type was used as a universal return type.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/__tests__/maybe-existing-repo.test.ts
> +      .mockResolvedValueOnce({ repoName: CREATE_REPO })
does this test that the user is asked again when the repo name is invalid ?
It so the name of the test is not clear enough, should be something like "it ask the users fora valid domain until it receives one"

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/__tests__/tsconfig.json
> +  "references": [{ "path": ".." }]
You should exclude the test from typescript original config and include them in this one so they wo'nt be transpiled and run twicer

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/index.ts
> +  await maybeExistingRepo(config.cookies, cwd, base);
The step should only takes what's coming from the core, the config should be retrieved in side the step itself to keep a clear execution in this file.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +export const CREATE_REPO = "$_CREATE_REPO"; // not a valid domain name
I understand that this value would be used in tests but i don't see what it has to do here.
I think it shouldn't be here at all, and tests shouldn't affect the code if that the only use of this variable.
But maybe i'm missing something.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +  return msg.join("");
please return a dynamic string for clarity.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +export function maybeRepoNameFromSMFile(cwd: string, base: string) {
I think this should be an helper from the Core package.
Maybe even one to get a repo from an endpoint and a helper on the Manifest file to retrieve it.
I'm guessing this will be used a bunch.
And i'm guessing if you need it then maybe you already have the Core at this point and it could be called from the directly.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +export function canUpdateCustomTypes(role: Communication.Roles) {
same, I would define that as a helper in the communication module.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +export function orderPrompts(maybeName?: string | null) {
I do understand the need for disabled but not for the Invalid repo name. I don't see how we could end up having to log that.

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +  // const sep: Separator = new inquirer.Separator(
remove unused code :)

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +    //  sep
same

2021-10-18 10:41 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +  const res = await inquirer.prompt<Record<string, string>>([
If there is no configured repo name then why wait for inquirer at all, why not just promptForCreateRepo directly ?

2021-10-19 14:29 UTC, Heyrows approved these changes

2021-10-20 15:56 UTC, Heyrows approved these changes

2021-10-20 15:56 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +  const hint = `${Utils.yellow("ℹ")}  ${Utils.dim(
I would have put it in the Core because I don't think this is the last hint we ever write.

2021-10-22 13:15 UTC, merged