Sm init create repo
prismicio/slice-machine pull request #189
Opened 2021-10-12 15:47 UTC by MarcMcIntosh

sm init script can now create a repository.

manual testing steps

```
git clone https://github.com/prismicio/slice-machine -b sm-init-create-repo
cd slice-machine
yarn
pushd packages/slicemachine-core
yarn build 
popd 
pushd packages/sm-init  
yarn build 
popd 
node packages/sm-init/build/index.js
```
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-10-14 15:21 UTC, Miniplop reviewed
Add the new line and put the ticket to validate

2021-10-14 15:21 UTC, Miniplop commented on packages/sm-init/src/steps/create-repo.ts
> +}
New line here

2021-10-15 11:28 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/create-repo.ts
> +}
done :)

2021-10-19 16:44 UTC, Heyrows approved these changes

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
>      jest.clearAllMocks();
I think we can remove this and use this in the afterEach instead

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +    test("default arguments", async () => {
i think the name should be a little more specific

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/core/communication.test.ts
> +      const framework = "foo-js";
these consts seems to be identical, I would declare them at beginning of the describe.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/jest.config.js
> +  clearMocks: true,
If I remember correctly this clear mock between tests.
i think it should be something we control rather than having it in the conf of jest.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> -// async function createRepository
didn't saw that in the original PR, good catch

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +  framework = "",
i think the default is vanilla JS, we have enums for that but I believe in the function to detect the framework, we use vanillaJS as default.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +  framework = "",
and this and the base below should be typed.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +    .post<
really don't like axios casting stuff, at some point we'll have to get rid of it and use io-ts.
I guess here it's pretty safe because it's a critical unchanged part of the application but still.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +        "User-Agent": "prismic-cli/sm",
i guess this should be either a parameter or a const but here for example the INIT is calling it, not the CLI.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/communication.ts
> +      if (axios.isAxiosError(error)) throw error;
if we throw error in both case, just throw the error :D.

2021-10-19 16:44 UTC, Heyrows commented on packages/slicemachine-core/src/core/index.ts
>      // create: (apiEndpoint: string, token: string) => Promise<void>
implement this please since you implemented the function that does the job itself :)

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/__tests__/create-repo-sm-core.test.ts
> +  Communication: {
I would use jest.requireActual instead of mocking the whole package.
It's on the best practices of jest :)

https://jestjs.io/fr/docs/jest-object#jestrequireactualmodulename
![image](https://user-images.githubusercontent.com/41187899/137951976-8cc9977c-ac54-4e66-81f0-f20010853b74.png)

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/__tests__/create-repo.test.ts
> +    const domain = "foo-bar";
again, i'd put that in the describe because it's common to all the test inside of it.

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/__tests__/create-repo.test.ts
> +  test("failure", async () => {
The name of the test should be more precise, which failure ?

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/__tests__/create-repo.test.ts
> +  test("success", async () => {
the name of the test should be more precise, it's a success but under which condition ?

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/__tests__/create-repo-sm-core.test.ts
> +test("mock core create repo", async () => {
name of the test is not clear enough, I would put something like "The mocked function 'create repository' of the Slicemachine-Core is being called."

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/src/index.ts
> +    config.base
Could you pass an AuthConfig as parameters instead of cookies and base :).

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/src/index.ts
> +    await createRepository(name, config.cookies, "framework", base);
same here, it's function created for the core so i think we can pass AuthConfig directly.
Weird that this. step was done before the framework if we actually need it haha.

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/src/steps/create-repo.ts
> +      if (error.response) {
Here I think we should have first the current error, and then the error that ask to run the command again.

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/src/steps/create-repo.ts
> +      if (error.response) {
This error is used in another step before, i think ti's the login

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/src/steps/create-repo.ts
> +      if (error.response) {
And I guess the process should be killed.

2021-10-19 16:44 UTC, Heyrows commented on packages/sm-init/src/steps/maybe-existing-repo.ts
> +  if (res.repoName === CREATE_REPO) {
awesome, i like the changes you made on the file.

2021-10-19 16:46 UTC, Heyrows requested changes
I did shit, didn't mean to approve haha

2021-10-19 16:50 UTC, Heyrows commented
Linter & tests are passing 👍  good

2021-10-19 16:58 UTC, Heyrows commented
After testing, the hint that is supposed to be displayed when typing the repository name doesn't appear.

2021-10-20 12:17 UTC, MarcMcIntosh commented
Fine I'll add the hint

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/slicemachine-core/jest.config.js
> +  clearMocks: true,
I don't mocks lingering around after one test as it may interferer with another.

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/slicemachine-core/jest.config.js
> +  clearMocks: true,
better safe than sorry ;)

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/communication.ts
> +  framework = "",
default parameters are typed automatically :)

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/communication.ts
> +      if (axios.isAxiosError(error)) throw error;
Pretty sure that was so it can throw an AxiosError when used

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/core/index.ts
>      // create: (apiEndpoint: string, token: string) => Promise<void>
I'll add it but are people going to be using the core to create new repos?

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/sm-init/__tests__/create-repo-sm-core.test.ts
> +  Communication: {
Yeah I saw that (and tried) I was wanting to check if mocking the core would work. but i don't advise doing it as we own the core and want to make sure it works as epxected

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/sm-init/__tests__/create-repo-sm-core.test.ts
> +test("mock core create repo", async () => {
Yeah i should make it more explicit

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +    config.base
Should we pass the whole thing when just a little bit of info is needed?

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +    await createRepository(name, config.cookies, "framework", base);
Yeah I the kyu project was a bit of an after thought here

2021-10-21 09:59 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/create-repo.ts
> +      if (error.response) {
Can do

2021-10-21 10:17 UTC, Heyrows approved these changes

2021-10-25 13:01 UTC, merged