feat(sm-init): add frame wrok detection
prismicio/slice-machine pull request #192
Opened 2021-10-14 09:34 UTC by MarcMcIntosh

Adds frame work detection before creating the repo
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-10-14 10:02 UTC, Miniplop commented on packages/slicemachine-core/src/utils/files.ts
> +      const result = Boolean(fs.lstatSync(pathToFile));
why creating a redondant variable here and not using the return ?

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/index.ts
> +  const framework = await detectFramework(cwd);
I think in the sketches the framework detection occurs after the repository creation. I see that you use the framework in the create repository. Maybe you should talk about that with the designers :)

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +  return maybeDetect(cwd)
can we use await + try catch syntax instead of mixing promise and await

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +        spinner.succeed(`Found: ${framework}`);
I think the correct wording is  `${framework} detected`

![image](https://user-images.githubusercontent.com/15800180/137294321-03d856c8-06b3-400e-a9ff-f1ecba399d6c.png)

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +  const spinner = Utils.spinner("Detecting framework");
The wording in the sketches is "Detecting your framework to install correct dependencies"

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +  const spinner = Utils.spinner("Detecting framework");
And I think this working is not correct in english right ?

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +      console.log(
I thought that we decide to use ora for instead of console.log for displaying message, did I miss something ?

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +    .catch(() => "") // or some other framework that's not supported
What is this case ? And maybe we should return the message `Please run npx slicemachine init in a Nuxt or Next.js project` in this case no ?

2021-10-14 10:02 UTC, Miniplop commented on packages/slicemachine-core/__tests__/src/utils/framework.test.ts
> +  test("it will return a support framework when a support framework is found in the package.json", () => {
Maybe we should have a test for each supported framework no ? To make sure they are all working good no ?

2021-10-14 10:02 UTC, Miniplop commented on packages/sm-init/__tests__/detect-framework.test.ts
> +import { describe, expect, test, jest, afterEach } from "@jest/globals";
what is the difference between testing the step or testing the utils in this case ? Do you some case where the step case become red and utils test stay green ?

2021-10-14 10:13 UTC, MarcMcIntosh commented on packages/sm-init/src/index.ts
> +  const framework = await detectFramework(cwd);
Yes, but for the KYU/CDP we need to know the framework before creating the repo :/

2021-10-14 10:16 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/utils/files.ts
> +      const result = Boolean(fs.lstatSync(pathToFile));
if fs throws it might not be caught by the catch block,
I've seen this before and it was pretty hard to track down.

2021-10-14 10:18 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +  const spinner = Utils.spinner("Detecting framework");
Maybe the `your` part..... unless they own the framework

2021-10-14 10:19 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +      console.log(
ora is for spinners right?

2021-10-20 07:38 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +      console.log(
My bad yes :)

2021-10-20 07:38 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +      throw new Error("frame work not-found");
typo => framework *

2021-10-20 07:38 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +      throw new Error("frame work not-found");
Why throw a new error here ?

2021-10-20 07:38 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +        )} in a Nuxt or Next.js project`
we support also react and vue project right ?

2021-10-20 07:38 UTC, Miniplop commented on packages/sm-init/src/index.ts
> +  const framework = await detectFramework(cwd);
Ok for that :)

2021-10-20 07:38 UTC, Miniplop commented on packages/sm-init/src/steps/detect-framework.ts
> +  return new Promise((resolve, reject) => {
As discussed with Arnaud, we dont see the value of casting the result of Utils.framework.detectFramework(cwd) to a promise.

2021-10-20 16:17 UTC, Miniplop approved these changes

2021-10-22 14:52 UTC, Heyrows requested changes

2021-10-22 14:52 UTC, Heyrows commented on packages/slicemachine-core/src/utils/framework.ts
> +  if (deps[Framework.gatsby]) return Framework.gatsby;
I wouldn't do that.
Gatsby might no be the only edge case like that that we encounter.
What we need to have is either have a list of all the frameworks, or have the main framework.

For that i see 2 functions, the one that detects all the frameworks, one that takes the main framework (depending on the list) and return if he is supported or not.

2021-10-22 14:52 UTC, Heyrows commented on packages/sm-init/src/steps/detect-framework.ts
> +      // spinner.fail();
remove comment :)

2021-10-22 14:52 UTC, Heyrows commented on packages/sm-init/src/steps/detect-framework.ts
> +    // spinner.stop();
remove comment

2021-10-22 14:52 UTC, Heyrows commented on packages/sm-init/src/steps/detect-framework.ts
> +      console.log(failMessage);
why not write it as an error anymore ?

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/slicemachine-core/__tests__/src/utils/framework.test.ts
> +  test("it will return a support framework when a support framework is found in the package.json", () => {
if you want to, sure I can do that :)

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/sm-init/__tests__/detect-framework.test.ts
> +import { describe, expect, test, jest, afterEach } from "@jest/globals";
In another PR I tried mocking slicemachine-core.... in this case it was easier to just use sm-core and mock fs.

The advantage with not mocking sm-core is that we'll know what breaks if the core changes.

But mostly I like having the coverage :)

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +    .catch(() => "") // or some other framework that's not supported
core throws errors and logs some info, I can take a look and see what else I can do

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +  return maybeDetect(cwd)
how you feel about nested try / catch blocks?

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +      console.log(failMessage);
Because the in the figma, the message is not prefixed be `Error!`

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +    // spinner.stop();
can do

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/sm-init/src/steps/detect-framework.ts
> +      // spinner.fail();
can do

2021-10-22 15:00 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/utils/framework.ts
> +  if (deps[Framework.gatsby]) return Framework.gatsby;
I'll see what i can do

2021-10-22 16:09 UTC, Heyrows requested changes
works as intended, I tested and it works nicely :)
The last thing to do is to call it before repo creation so we have the info about the framework on repo creation.

2021-10-22 16:20 UTC, Heyrows approved these changes
My bad, didn't understand that we ask for the repo name but don't create it straight away.

2021-10-26 15:39 UTC, merged