AAUser, when my connexion token expires, I can login from SM UI
prismicio/slice-machine pull request #193
Opened 2021-10-15 09:35 UTC by Miniplop

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-10-15 14:57 UTC, Miniplop commented
![image](https://user-images.githubusercontent.com/15800180/137508386-74b668b5-5557-4461-90d0-1b6f08a9cda4.png)

2021-10-20 14:25 UTC, Heyrows requested changes

2021-10-20 14:25 UTC, Heyrows commented on .husky/pre-commit
> +npx lint-staged
I think we should use `npm lint-staged`.
That way we controle which version of the package is used and if one day we decide to change this will throw an error right away because the package isn't installed.

2021-10-20 14:25 UTC, Heyrows commented on Makefile
> +.PHONY: install
What's the use of this file ?
Seems like a CI thing but i'm not sure.

2021-10-20 14:25 UTC, Heyrows commented on package.json
> +    "fp-ts": "^2.11.4",
I don't think we need this io-ts and fp-ts at this level, there is no code here :).

2021-10-20 14:25 UTC, Heyrows commented on package.json
> -    "postinstall": "lerna bootstrap",
i think this command was there to be executed automatically by npm.
Are we sure we want to delete it.

2021-10-20 14:25 UTC, Heyrows commented on packages/next-slicezone/package.json
> +    "audit": "better-npm-audit audit -l high -p",
I know that for yarn you need to do a `yarn module` to call a node module, isn't it the same for Npm ? (tbh I don't know, that's a question 😄 )

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +const poll = async (
I'm pretty sure you made a Poll function in the core already.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +const poll = async (
Or at least I saw one on a PR of Marc and it had been refactored for linter issues.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +type LoginModalProps = {
type vs interface that is the question
https://stackoverflow.com/questions/37233735/interfaces-vs-types-in-typescript

I don't mind if it remains a type, I usually use interface rather than type.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +const poll = async (
I would at least put it in another file so that when Marc's PR is merged, we just need to change the import

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +import Prismic from "components/AppLayout/Navigation/Icons/Prismic";
I think the path should be relative.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +      await fetch("/api/auth/start", { method: "POST" });
It could be good to have an endpoint module with all the routes shared by the serveur and the UI maybe.
That way if one route change it doesn't break everything.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +      window.open(
just a suggestion but maybe we could close the window when the poll return a true.
Originally the dashboard page has a success message when you're logged in but maybe we can close it here and the user would just see the popup disappear

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +      window.open(
```suggestion
      const tab = window.open('blabla')
      tab.close()
```

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +      await poll(checkStatus, isAuthStatusOk, 3000, 60);
i'm wondering if we can still nagivate while it polls. To test

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +      addToast("Logging successfully", { appearance: "success" });
Are sure about the success/fail messages.
There are so many ways to write the action of logging in that i'm never sure which one is good.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +            In to order to perform this action, you’ve to be connected into your
`you've got to be connected` or `you need to be connected`.
Maybe `with` instead of `Into`

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/lib/builders/CustomTypeBuilder/Layout/Header.tsx
> +              if (!data.done) {
if the done symbolise that everything is Pushed, if you return before an error or the status is checked, the popup will never open no ?

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/lib/builders/SliceBuilder/index.jsx
> +    setData(data);
I would set the data only if there is no error.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/lib/builders/SliceBuilder/index.jsx
> +    if (data.error && (data.status === 401 || data.status === 403)) {
To me 401 means you're not connected while 403 means you don't have the right to do that.
I wouldn't open the login for a 403

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/package.json
> +    "lint:precommit": "eslint",
wouldn't the commit fail if we don't have the max-warning ?
Why not put it there ?

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/pages/[lib]/[sliceName]/[variation].tsx
> +const SliceEditor: React.FunctionComponent<{
That's a personal preference but I like to have the interface/type of a component above it.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/pages/_app.tsx
> +                <ToastProvider>
Just for my knowledge because I didn't worked much with contexte before, the provider is a component that adds the context to the property of the children ?

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/pages/cts/[ct].tsx
> +const CustomTypeBuilderWithProvider: React.FunctionComponent<CustomTypeBuilderWithProviderProps> =
I like the changes on this file, a quick refacto but a nice one !!

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/auth/post.ts
> +const AuthRequest = t.type({
I love that

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/auth/post.ts
> +type AuthRequest = { email: string; cookies: string[] };
You can do this, it's cooler and we never redefine twice the type :)
```suggestion
 type AuthRequest = t.TypeOf<typeof AuthRequest>
```

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/auth/post.ts
> +export default async function handler(authRequest: {
Io-Ts usually takes an object, a record or an unknown to decode.

Here I'm guessing you're casting the shape of the authRequest but it seems that here you know already it's an AuthRequest.

I would suggest:
- if you know the type of auth request for sure, like you call the function yourself, then don't use io-ts because you already have you data
- If you don't know and it's casting, then put authRequest as Record<string, unknown>, that would be more accurate to the situation.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/auth/post.ts
> +    const authPayload = fold(
Here I would just return the fold without a try.
In case of error, you can send back the object { err }
In case of success you can setTheAuthConfigCookie and then return the error

I would also set the base here.
If someone had previously logged in stage and now use the prod, this wouldn't work.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/auth/start.ts
> +    // Reset the prismic auth cookie
I would not set just the cookie, the base might not be right.

Let's say you were connected on stage and now you're playing with the prod, the UI will detect you're not connected but this will only reset the cookies, not the base.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/custom-types/push.ts
> -      status: 500,
I would put back the code there was with
```
 status: state.clientError ? state.clientError.status : 403
```

Should it be 403 tho ?
No connected usually means 401

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/index.ts
> +      return res.status(payload.status).json(payload);
I did not check all the files yet, but if this send a 401 and not a 400 which is. good, I hope the front will still react the same way

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/index.ts
> +      return res.status(400).json({});
i guess it was used like that before but i don't like the idea of sending a 400 when we have a potential error.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/index.ts
> +    return res.status(200).json(payload);
I would return an error if the status was an error.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/slices/push.ts
> +      "[slice/push] Could not fetch remote custom types. Are you logged in to Prismic?";
remote slices*

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/slices/push.ts
> +    return {
I would use the OnError function that was made and used in this same file.

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/slices/push.ts
> +  if (env.client.isFake()) {
I'm not sure to see why we need a specific case for the fake env.

What's a fake env ?
I can't think of anything but the dev environment

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/index.ts
> +app.use(cors());
I would use Cors as the first middleware of the app, so we don't use the bordy parser for nothing :)

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/index.ts
> +app.use(cors());
It's a good point to have added that.

2021-10-20 14:25 UTC, Heyrows commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function setAuthConfigCookies(
I think this function shouldn't exist, it was wrong of me to use the name cookies

2021-10-20 14:25 UTC, Heyrows commented on packages/slicemachine-core/src/filesystem/authConfig.ts
>    base: string,
maybe we could send an authConfig instead of base + cookie directly.

2021-10-20 14:25 UTC, Heyrows commented on packages/slicemachine-core/src/filesystem/authConfig.ts
>    base: string,
or maybe event a Partial AuthConfig

2021-10-20 14:25 UTC, Heyrows commented on packages/sm-init/package.json
> +    "audit": "better-npm-audit audit -l high -p",
I noticed that all subpackages don't have an audit fix, it might be worth adding one to use lerna to fix everything quickly

2021-10-20 14:25 UTC, Heyrows commented on packages/slice-machine/server/src/api/auth/status.ts
> +    const authResult = parseAuth(authConfig.cookies);
We have a cookie Module inside the Core, i think this function should be on it.

2021-10-20 14:33 UTC, Miniplop commented on package.json
> +    "fp-ts": "^2.11.4",
oh, that lerna troll

2021-10-20 14:34 UTC, Miniplop commented on package.json
> +    "fp-ts": "^2.11.4",
I will fix it

2021-10-20 14:34 UTC, Miniplop commented on package.json
> -    "postinstall": "lerna bootstrap",
Look at 2 lignes above :p

2021-10-20 15:22 UTC, Miniplop commented on packages/next-slicezone/package.json
> +    "audit": "better-npm-audit audit -l high -p",
in npm you can call a module directly

2021-10-20 15:24 UTC, Miniplop commented on packages/slice-machine/server/src/index.ts
> +app.use(cors());
I don't know if the use order change the priority order for the middleware, but I don't think so. Anyway I can change it, if it make it clearer

2021-10-20 15:24 UTC, Miniplop commented on packages/sm-init/package.json
> +    "audit": "better-npm-audit audit -l high -p",
good point 👍

2021-10-20 15:25 UTC, Miniplop commented on packages/slice-machine/server/src/api/auth/status.ts
> +    const authResult = parseAuth(authConfig.cookies);
good catch

2021-10-20 15:35 UTC, Miniplop commented on Makefile
> +.PHONY: install
Nop it's a file for creating make command to ease the installation process and other painfull processes

2021-10-20 15:36 UTC, Miniplop commented on package.json
> +    "fp-ts": "^2.11.4",
Done

2021-10-20 15:36 UTC, Miniplop commented on packages/slice-machine/server/src/index.ts
> +app.use(cors());
Done

2021-10-20 15:37 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +type LoginModalProps = {
I can change it yes

2021-10-20 15:38 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +import Prismic from "components/AppLayout/Navigation/Icons/Prismic";
The icon was deleted

2021-10-20 15:40 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +            In to order to perform this action, you’ve to be connected into your
The wording was changed

2021-10-20 15:41 UTC, Miniplop commented on packages/slice-machine/lib/builders/CustomTypeBuilder/Layout/Header.tsx
> +              if (!data.done) {
done in this case simbolise that the request ended, but the response can be an error

2021-10-20 15:43 UTC, Miniplop commented on packages/slice-machine/lib/builders/SliceBuilder/index.jsx
> +    if (data.error && (data.status === 401 || data.status === 403)) {
I need to check that but I think there is a confusion in the API around the status code

2021-10-20 15:46 UTC, Miniplop commented on packages/slice-machine/package.json
> +    "lint:precommit": "eslint",
As we run the linter only on file staged the max warnings flag is not useful. It will be ok except if you change all the files in one commit 🤯.

I think the issue is more  that the lint:precommit command won't crash because every linter errors is now cast to warnings in this package :)

2021-10-20 15:46 UTC, Miniplop commented on packages/slice-machine/pages/_app.tsx
> +                <ToastProvider>
Yes 💪

2021-10-20 15:47 UTC, Miniplop commented on packages/slice-machine/pages/cts/[ct].tsx
> +const CustomTypeBuilderWithProvider: React.FunctionComponent<CustomTypeBuilderWithProviderProps> =
♥️

2021-10-20 15:47 UTC, Miniplop commented on packages/slice-machine/server/src/api/auth/post.ts
> +const AuthRequest = t.type({
Oh yeah 🤟

2021-10-20 15:48 UTC, Miniplop commented on packages/slice-machine/server/src/api/auth/post.ts
> +type AuthRequest = { email: string; cookies: string[] };
Ohhh love that

2021-10-20 16:40 UTC, Miniplop commented on .husky/pre-commit
> +npx lint-staged
Good point I follow the lint-staged but we can improve this :)

2021-10-20 16:40 UTC, Miniplop commented on .husky/pre-commit
> +npx lint-staged
Done

2021-10-20 16:43 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +const poll = async (
Yes I think that should be changed when we will merge the branch 🧙‍♂️

2021-10-20 16:51 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +      await fetch("/api/auth/start", { method: "POST" });
Yes good point I just start this by creating a apiClient module

2021-10-20 16:58 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +      window.open(
I think this is a little bit brutal to close the dashboard success login page without asking :p

2021-10-20 17:00 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +      await poll(checkStatus, isAuthStatusOk, 3000, 60);
I tested and tested the polling continue if you navigate :) You think this is a problem ?

2021-10-20 17:02 UTC, Miniplop commented on packages/slice-machine/components/LoginModal/index.tsx
> +      addToast("Logging successfully", { appearance: "success" });
I change it to "logged in" => I take this wording from the dashboard :)

2021-10-20 17:13 UTC, Miniplop commented on packages/slice-machine/lib/builders/SliceBuilder/index.jsx
> +    if (data.error && (data.status === 401 || data.status === 403)) {
For push slice : 
- You have a 403 if don't have any credentials in your ~/.prismic file or if your token has expired
- You have a 401 if don't have the right to access to the repository

Same for the custom types. I notice this is the opposite of what 401 and 403 is :)

So for me we should display the login only on 403 and not on 401 where we should display a error message to ask for changing to repo. Are you ok with that ?

2021-10-20 17:46 UTC, Miniplop commented on packages/slice-machine/server/src/api/auth/post.ts
> +export default async function handler(authRequest: {
Yeah I think Record<string, unknown> is more accurate

2021-10-20 17:47 UTC, Miniplop commented on packages/slice-machine/server/src/api/auth/post.ts
> +type AuthRequest = { email: string; cookies: string[] };
Fixed :)

2021-10-20 17:49 UTC, Miniplop commented on packages/slice-machine/server/src/api/slices/push.ts
> +      "[slice/push] Could not fetch remote custom types. Are you logged in to Prismic?";
fixed :)

2021-10-20 17:50 UTC, Miniplop commented on packages/slice-machine/server/src/api/slices/push.ts
> +  if (env.client.isFake()) {
Fake env is when the user don't have any token in the prismic file

2021-10-20 17:53 UTC, Miniplop commented on packages/slice-machine/server/src/api/slices/push.ts
> +  if (env.client.isFake()) {
I don't like this concept, I found it very confusing and not scalable as the fake client should always follow the same interface that the Default client. I think the case where the user don't has a correct prismic file should be handle by an another solution.

2021-10-20 18:01 UTC, Miniplop commented on packages/slice-machine/server/src/api/index.ts
> +      return res.status(400).json({});
Yep I send now a 500

2021-10-20 18:01 UTC, Miniplop commented on packages/slice-machine/server/src/api/index.ts
> +    return res.status(200).json(payload);
Yeah good one :)

2021-10-20 18:02 UTC, Miniplop commented on packages/slice-machine/server/src/api/index.ts
> +      return res.status(payload.status).json(payload);
There isn't any condition on the fronts on error status (except login now)

2021-10-21 07:34 UTC, Miniplop commented on packages/slice-machine/lib/builders/SliceBuilder/index.jsx
> +    setData(data);
I don't like this callback but it seems the interface need to have information even if there is an error

2021-10-21 07:35 UTC, Miniplop commented on packages/slice-machine/pages/[lib]/[sliceName]/[variation].tsx
> +const SliceEditor: React.FunctionComponent<{
Done :)

2021-10-21 07:37 UTC, Miniplop commented on packages/slice-machine/server/src/api/custom-types/push.ts
> -      status: 500,
I change this to match the slice route behavior : 
- 401 => Mean you are not logged in
- 403 => Mean you don't have the good right

2021-10-21 07:44 UTC, Miniplop commented on packages/slice-machine/server/src/api/slices/push.ts
> +    return {
We cannot use this function, because the status of the error is coming from the error itself. 

`export const onError = (
  r: Response | FakeResponse | null,
  message = "Unspecified error occurred."
) => ({
  err: r || new Error(message),
  status: r && r.status ? r.status : 500,
  reason: message,
})`

At the moment, we don't have any tool for creating http error with a status as the `http-errors` lib. And that seens a little bit overkill to do so. We can also add a new param `status` to this function. What do you think ?

2021-10-21 08:44 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +      window.open(
Ok

2021-10-21 10:59 UTC, Miniplop commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +export function setAuthConfigCookies(
Fixed :)

2021-10-21 10:59 UTC, Miniplop commented on packages/slicemachine-core/src/filesystem/authConfig.ts
>    base: string,
I used optional param to do so

2021-10-21 11:00 UTC, Miniplop commented on packages/slice-machine/server/src/api/auth/start.ts
> +    // Reset the prismic auth cookie
As we saw the SM server use for now this information for calling the right endpoint. We will change this behavior when using SM.json repo as the reference for the base

2021-10-21 11:10 UTC, Miniplop commented on packages/slice-machine/server/src/api/slices/push.ts
> +    return {
Fixed

2021-10-21 14:41 UTC, Heyrows requested changes

2021-10-21 14:41 UTC, Heyrows commented on packages/slice-machine/lib/auth.ts
> +        return { base: prismicFile.base, auth: { auth: authResult } };
are you sure about this ?
Does that means we are calling `object.auth.auth` ?

2021-10-21 14:41 UTC, Heyrows commented on packages/slice-machine/lib/builders/CustomTypeBuilder/Layout/Header.tsx
> +              handleRemoteResponse(addToast)(data);
i'm still not understanding totally why we have to call handlers if the response can be an error.
Shouldn't all error case be handled here ? (might not be due to your development but i'm asking the question again).

2021-10-21 14:41 UTC, Heyrows commented on packages/slice-machine/pages/[lib]/[sliceName]/[variation].tsx
> +  openPanel: (priority?: any) => void;
ouch, that's an any.

2021-10-21 14:41 UTC, Heyrows commented on packages/slice-machine/server/src/api/custom-types/push.ts
> +    const errorCode = state.isFake
I think here we could do `errorCode = state.clientError?.status || 403`

2021-10-21 14:41 UTC, Heyrows commented on packages/slicemachine-core/__tests__/src/utils/cookie.test.ts
> +    jest.clearAllMocks();
If you have an afterEach, an afterAll is not needed :)

2021-10-21 14:41 UTC, Heyrows commented on packages/slicemachine-core/src/utils/cookie.ts
> +const AUTH_KEY = "prismic-auth";
this could / should be in the const file or the utils

2021-10-21 14:41 UTC, Heyrows commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +    base: !!base ? base : currentConfig.base,
Base is a `string | undefined`, you can just have
```suggestion
    base: base ? base : currentConfig.base,
```

or 

```suggestion
    base: base || currentConfig.base,
```

2021-10-21 14:41 UTC, Heyrows commented on packages/slicemachine-core/src/filesystem/authConfig.ts
> +function formatCookies(cookies: ReadonlyArray<string>) {
no type of return.

I'm not sure but shouldn't this be in the Cookie file ?

2021-10-21 15:13 UTC, Miniplop commented on packages/slice-machine/lib/auth.ts
> +        return { base: prismicFile.base, auth: { auth: authResult } };
unfornately yes :/

2021-10-21 15:15 UTC, Miniplop commented on packages/slice-machine/pages/[lib]/[sliceName]/[variation].tsx
> +  openPanel: (priority?: any) => void;
oui :/

2021-10-21 15:21 UTC, Miniplop commented on packages/slice-machine/pages/[lib]/[sliceName]/[variation].tsx
> +  openPanel: (priority?: any) => void;
openPanel is coming from the _app.tsx with this typing : 

```
const openPanel = useCallback(
    (priority?: any) =>
      setDrawerState({
        ...drawerState,
        open: true,
        ...(priority ? { priority } : null),
      }),
    []
  );
```

2021-10-21 16:39 UTC, Miniplop commented
100 ! 🤟

2021-10-21 16:46 UTC, Heyrows approved these changes
disruption

2021-10-25 12:25 UTC, Miniplop commented
Loading state with the manual link 

![image](https://user-images.githubusercontent.com/15800180/138694540-b6e9afdf-5667-4ff2-862d-52351352b669.png)

2021-10-25 14:26 UTC, Heyrows approved these changes

2021-10-25 14:26 UTC, Heyrows commented on packages/slice-machine/components/LoginModal/index.tsx
> +                  Go back and try again
i'm not an expert in design so what i'm saying might be complete shit. 😄 
But usually I see something more like `Didn't the tab open automatically ? <link>Open it manually</link>`

2021-10-26 15:58 UTC, merged