AAUser, I want to launch SM on local host 9999 when I run SM start
prismicio/slice-machine pull request #194
Opened 2021-10-20 13:52 UTC by Miniplop

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-10-20 13:57 UTC, Miniplop commented
The CI is failing because of yarn link not working with the audit, we should merge the PR on login before this one

2021-10-21 12:25 UTC, MarcMcIntosh commented
Why would it work on other branches but fail on this one?

2021-10-21 13:52 UTC, Miniplop commented
Because in your branches you didn't have the slicemachine core installed in the sm ui which make the audit fail. And in the login branch I migrate to npm to solve this problem :)

2021-10-22 08:48 UTC, Miniplop commented
I installed the sm in a project with node v12.22.7, works fine. I also noticed with node 12 with have issue to run the local env due to next platform requirement.

2021-10-22 13:27 UTC, Heyrows requested changes

2021-10-22 13:27 UTC, Heyrows commented on packages/slice-machine/lib/models/common/http/DefaultClient.ts
> +  PROD: "https://tracking.prismic.io",
stupid question probably but has the tracking repository domain be reserved ? (PR on wroom).
Because if the repo already exists, we cannot use that address :D

2021-10-22 13:27 UTC, Heyrows commented on packages/slicemachine-core/src/filesystem/manifest.ts
> +  framework?: Framework.Framework;
feels like it's prettier that wrote that, but it's giving me chills 😂

2021-10-22 13:27 UTC, Heyrows commented on packages/slicemachine-core/src/utils/index.ts
> +export * as Framework from "./framework";
I usually love to have a module, but here to avoid `Framework.Framework` or `Framework.detectFramework` I would `export * from './framework'`

2021-10-22 13:27 UTC, Heyrows commented on packages/slice-machine/start/index.js
>      console.log("[slice-machine] Thanks for using SliceMachine");
never actually saw that one because I usually stop with `Ctrl+C`
I think it would be a nice touch to have it on `Ctrl+C` too :)
https://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits

2021-10-22 13:27 UTC, Heyrows commented on packages/slice-machine/start/index.js
>    }
This comment is for 2 lines below the `const userConfig = handleManifest(cwd);`

I know it's not you but Man the handleManifest function is imported from the build directly T_T
I think the function that gives a state about the manifest should be in the core.

2021-10-22 13:27 UTC, Heyrows commented on packages/slice-machine/start/index.js
> +      console.log(`Run "npx sm init" command to configure your project`);
The current message we have everywhere is `console.log(Run ${bold("npx slicemachine init")} again!);`
I guess we either need to have the command as a CONST so that we don't all write different things, and we need to have it bold here for you :).

2021-10-22 13:28 UTC, Miniplop commented on packages/slice-machine/lib/models/common/http/DefaultClient.ts
> +  PROD: "https://tracking.prismic.io",
The tracking service is already deployed on this address :)

2021-10-22 14:06 UTC, Heyrows commented on packages/slice-machine/lib/models/common/http/DefaultClient.ts
> +  PROD: "https://tracking.prismic.io",
We have a system in Wroom that keep some domain from being taken, that's what I meant :)

2021-10-22 14:08 UTC, Miniplop commented on packages/slice-machine/start/index.js
> +      console.log(`Run "npx sm init" command to configure your project`);
Can be a good idea yes

2021-10-22 14:08 UTC, Miniplop commented on packages/slice-machine/start/index.js
>    }
Yeah this is normal as this file is not yet transpiled by webpack

2021-10-22 14:08 UTC, Miniplop commented on packages/slicemachine-core/src/utils/index.ts
> +export * as Framework from "./framework";
I think we should choose one way for accessing sub module and don't a mix  : 

- option 1 : we defined namespace for each
- option 2 : we use wildcard to have one big utils object

What is your opinion ? 

For the type I'm not comfortable of having the types spread into the submodules, because that also mean importing all the functions with it. I think we should have a type module for sharing types.

2021-10-22 14:08 UTC, Miniplop commented on packages/slicemachine-core/src/filesystem/manifest.ts
> +  framework?: Framework.Framework;
As I said in the next comment, I think we should have something like Types.Framework or exposing types on the core itself

2021-10-22 14:13 UTC, Heyrows commented on packages/slicemachine-core/src/utils/index.ts
> +export * as Framework from "./framework";
I like defined namespace for each, I prefer it that way actually but i know hugo was against.
I like the idea of having a type submodule, we could import it and use it like `Type.Framework`, or even import like `{ Framework } from type`.
But that would require making it :) and eventually taking all the type we currently have into it.

2021-10-22 14:13 UTC, Miniplop commented on packages/slice-machine/start/index.js
>      console.log("[slice-machine] Thanks for using SliceMachine");
Ctrl+C already works to shut down the server

2021-10-22 14:13 UTC, Heyrows commented on packages/slice-machine/start/index.js
>    }
hmmmm Ok i see.

2021-10-22 15:17 UTC, Miniplop commented on packages/slice-machine/start/index.js
>      console.log("[slice-machine] Thanks for using SliceMachine");
As we removed the message this is not relevant now :)

2021-10-22 15:18 UTC, Miniplop commented on packages/slice-machine/lib/models/common/http/DefaultClient.ts
> +  PROD: "https://tracking.prismic.io",
So I imagine this domain is not taken as this endpoint is working :p 😂

2021-10-25 09:30 UTC, Miniplop commented on packages/slice-machine/start/index.js
> +      console.log(`Run "npx sm init" command to configure your project`);
Done

2021-10-25 09:30 UTC, Miniplop commented on packages/slicemachine-core/src/utils/index.ts
> +export * as Framework from "./framework";
Done

2021-10-25 09:53 UTC, Heyrows commented on packages/slice-machine/package.json
> +    "ora": "^6.0.1",
are you sure you need that ?
Because Utils.spinner is basically calling ora.
I think it's better to use the utils so if one day we change we need to change one place.

2021-10-25 09:53 UTC, Heyrows commented on packages/slicemachine-core/src/utils/const.ts
> +export const INIT_COMMAND = "npx sm init";
I'm pretty sure this is being used in most of the error message of the init so we might have to verify before releasing that this is used everywhere.

2021-10-25 09:53 UTC, Heyrows commented on packages/slicemachine-core/package.json
> +    "ora": "^5.4.1"
it's already a dependency, why does it need to be a peer dependency ?

2021-10-25 09:55 UTC, Miniplop commented on packages/slicemachine-core/src/utils/const.ts
> +export const INIT_COMMAND = "npx sm init";
mmmm I don't think it in the sm-init, maybe this is added by the ls-repos branch or non merged branch no ?

2021-10-25 09:56 UTC, Miniplop commented on packages/slicemachine-core/package.json
> +    "ora": "^5.4.1"
Because I want that when you install the core you install ora too

2021-10-25 09:56 UTC, Miniplop commented on packages/slicemachine-core/package.json
> +    "ora": "^5.4.1"
But this is not compatible with lerna, so we can remove this

2021-10-25 09:57 UTC, Miniplop commented on packages/slice-machine/package.json
> +    "ora": "^6.0.1",
Because we need ora to import utils in the start

2021-10-25 10:19 UTC, Heyrows approved these changes

2021-10-25 15:30 UTC, Heyrows approved these changes

2021-10-27 11:14 UTC, merged