AAuser, when I open SM for the first time, I see a /onboarding page empty
prismicio/slice-machine pull request #195
Opened 2021-10-21 16:19 UTC by hypervillain

Read onboarding state from localstorage and redirect to /onboarding.
Once onboarding page is loaded, add a line in localstorage that states user did see the onboarding

2021-10-22 12:57 UTC, Miniplop reviewed
Nice, one little mistake and you can pass this ticket to need test. Can you change the PR title to the User story title ? :)

2021-10-22 12:57 UTC, Miniplop commented on packages/slice-machine/pages/onboarding.tsx
> +    localStorage.setItem(LocalStorageKeys.isOnboarded, "yes");
can we use true boolean here instead of "yes" ?

2021-10-22 12:58 UTC, hypervillain commented on packages/slice-machine/pages/onboarding.tsx
> +    localStorage.setItem(LocalStorageKeys.isOnboarded, "yes");
I don't think you can store booleans in local storage

2021-10-22 12:58 UTC, hypervillain commented on packages/slice-machine/pages/onboarding.tsx
> +    localStorage.setItem(LocalStorageKeys.isOnboarded, "yes");
do you mean you want the string to have val "true"?

2021-10-22 14:07 UTC, Miniplop commented on packages/slice-machine/pages/onboarding.tsx
> +    localStorage.setItem(LocalStorageKeys.isOnboarded, "yes");
Yes good for me :)

2021-10-22 14:25 UTC, MarcMcIntosh requested changes

2021-10-22 14:25 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/manifest.ts
> -
why delete this?

2021-10-22 14:31 UTC, hypervillain commented on packages/slicemachine-core/src/filesystem/manifest.ts
> -
I didn't like the name of the function

2021-10-22 14:33 UTC, MarcMcIntosh commented on packages/slicemachine-core/src/filesystem/manifest.ts
> -
do you have any ideas what a better name would be?

2021-10-22 14:48 UTC, hypervillain commented on packages/slicemachine-core/src/filesystem/manifest.ts
> -
Sorry it wasn't clear: I was joking, this was a manual merge issue

2021-10-25 08:34 UTC, Heyrows commented
Should be from a branch 0.1.2

2021-10-25 15:08 UTC, MarcMcIntosh approved these changes

2021-10-26 16:59 UTC, Miniplop approved these changes

2021-10-26 16:59 UTC, Miniplop commented on packages/slice-machine/tests/project/cypress/integration/0-is-running/00-onboarding.spec.js
> +  it('when is-onboarded is in loal storge it should not redirect', () => {
typo storge and loal

2021-10-26 17:49 UTC, MarcMcIntosh commented on packages/slice-machine/tests/project/cypress/integration/0-is-running/00-onboarding.spec.js
> +  it('when is-onboarded is in loal storge it should not redirect', () => {
fixed :)

2021-10-27 16:34 UTC, merged