Onboarding slideshow Skeleton
prismicio/slice-machine pull request #196
Opened 2021-10-22 14:17 UTC by hypervillain

Add a Grid skeleton for the Onboarding slideshow

2021-10-25 08:34 UTC, Heyrows commented
Should be from a branch v0.1.2

2021-10-28 09:24 UTC, Heyrows requested changes

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/pages/onboarding.tsx
> +        {!!state.step && (
I might have missed it but I don't see the button to go back on the previous slide.

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/pages/onboarding.tsx
> +          <Button
According to the figma, the back button shouldn't appear on the first slide.
Given that behavior, we could image that the last button doesn't appear on the last slide or that he would redirect you out the onboarding if you click continue on the last slice.

That's a supposition, to see with ccome and benjamin but I don't think i've seen that behavior so far.

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/pages/onboarding.tsx
> +    if (state.step === STEPS.length) {
alright, that's what I missed, i guess this useEffect will make you leave the onboarding if you click the continue button on the last slide.

I think I would modify the onclik function rather than having a useEffect that runs all the time.

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/public/insert_page_break.svg
> +</svg>
sorry I didn't knew where to put this comment.
I think the names of the video are not really explicit and you can't see their importance unless you go in the code to find where it's.
Also, there are 2 SM-LOGO file, an Svg and a Png, i'm guessing one of them is not used.

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/pages/onboarding.tsx
> +const Video = (props: React.VideoHTMLAttributes<HTMLVideoElement>) => {
I'm not a fan of having all the components in one file but that's a personal opinion.
A side question, I couldn't find in this PR the line of code that tell SM to start on this page if the user hasn't seen the onboarding, do you know where it is located :) ?

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/tests/project/cypress/integration/0-is-running/00-onboarding.spec.js
> +  })
nice test, just an idea for a new one, the skip button :).

2021-10-28 09:24 UTC, Heyrows commented on packages/slice-machine/tests/project/cypress/integration/0-is-running/00-onboarding.spec.js
> +  })
Not mandatory, just saying that because I thought of it.

2021-10-28 09:26 UTC, MarcMcIntosh commented on packages/slice-machine/pages/onboarding.tsx
> +        {!!state.step && (
There wasn't one in the design

2021-10-28 09:28 UTC, MarcMcIntosh commented on packages/slice-machine/pages/onboarding.tsx
> +const Video = (props: React.VideoHTMLAttributes<HTMLVideoElement>) => {
I think it's in _app.ts or _document.ts

2021-10-28 09:29 UTC, MarcMcIntosh commented on packages/slice-machine/tests/project/cypress/integration/0-is-running/00-onboarding.spec.js
> +  })
skip button is in another ticket

2021-10-28 09:30 UTC, MarcMcIntosh commented on packages/slice-machine/pages/onboarding.tsx
> +        {!!state.step && (
oh wait there is it's just in an odd place

2021-10-28 10:24 UTC, Heyrows commented on packages/slice-machine/tests/project/cypress/integration/0-is-running/00-onboarding.spec.js
> +  })
ok :)

2021-10-28 10:36 UTC, MarcMcIntosh commented on packages/slice-machine/public/insert_page_break.svg
> +</svg>
The png isn't used in the code, but it does render in IDE's, which make's it easier to use.
I can remove it

2021-10-28 10:38 UTC, MarcMcIntosh commented on packages/slice-machine/pages/onboarding.tsx
> +          <Button
On the last slide the `contine` button redirects to `/`

2021-10-28 11:47 UTC, Heyrows approved these changes
Good :).
Do you think that the videos can increase the build time ?

2021-10-28 11:50 UTC, Heyrows commented
If we ever had more onboarding part on the application, we would definitely need to rename those videos to avoid having confusions.

2021-10-28 12:26 UTC, MarcMcIntosh commented
I don't think the videos will increase build time, as there not processed, just copied to the out-put directory.
Although I would ave to check web-packs internals to find out more

2021-10-28 13:31 UTC, merged