Fix: Puppeteer waits for root element to display and not for network …
prismicio/slice-machine pull request #271
Opened 2021-12-14 10:58 UTC by Heyrows

…idle

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2021-12-14 13:37 UTC, Miniplop approved these changes

2021-12-14 15:44 UTC, hypervillain commented
- "Nuxt has a websocket so we are more flexible on the network now": I have zero clue what this means
- "the library state is now generated after trying to take the screenshots" does not explain why
- "to avoid having a lot of pages opens on the puppeteer browser" is probably related to websockets but how?

2021-12-14 15:45 UTC, hypervillain requested changes

2021-12-14 15:45 UTC, hypervillain commented on packages/slice-machine/server/src/api/screenshots/puppeteer.ts
> +      waitUntil: "networkidle2", // websocket open for webpack in nuxt.
This comment does not really give information on why it's that way now

2021-12-15 10:11 UTC, hypervillain approved these changes
PR description was really helpful, thanks!

2021-12-15 10:11 UTC, merged