Fix "create CustomType" form
prismicio/slice-machine pull request #302
Opened 2022-01-18 14:26 UTC by hypervillain

- Check for empty ID values
- Set label as ID of not set
- Fix a regression that inverted the condition of "create CT" display

2022-01-19 11:37 UTC, MarcMcIntosh requested changes

2022-01-19 11:37 UTC, MarcMcIntosh commented on packages/slice-machine/tests/project/cypress/integration/pages/cts.spec.js
> +    cy.get('[create-ct]').click()
missing `data-cy` part of the selector

2022-01-19 12:45 UTC, MarcMcIntosh requested changes

2022-01-19 12:45 UTC, MarcMcIntosh commented on packages/slice-machine/tests/project/cypress/integration/pages/cts.spec.js
> +describe("onboarding skip", () => {
bad name as well

2022-01-20 12:22 UTC, Miniplop commented on packages/slice-machine/tests/project/cypress/integration/pages/cts.spec.js
> +    cy.get('[create-ct]').click()
Fixed

2022-01-20 12:23 UTC, Miniplop commented on packages/slice-machine/tests/project/cypress/integration/pages/cts.spec.js
> +describe("onboarding skip", () => {
Fixed

2022-01-20 13:06 UTC, MarcMcIntosh approved these changes

2022-01-20 13:49 UTC, merged