Mm/tracking create custom type
prismicio/slice-machine pull request #461
Opened 2022-05-06 09:30 UTC by MarcMcIntosh

Notes on write the tests, i found some errors/warnings in my the console that happen when opening the custom-type creation form.

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

2022-05-06 10:46 UTC, Heyrows requested changes

2022-05-06 10:46 UTC, Heyrows commented on packages/slice-machine/components/Forms/CreateCustomTypeModal.tsx
> +    // notes repo name could be empty, and will the tracker be initialized?
Is this a question for the reviewer or are you stating something 😄 ?

2022-05-06 10:46 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +  trackCreatCustomType(customTypeInfo: {
```suggestion
  trackCreateCustomType(customTypeInfo: {
```

2022-05-06 10:46 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +// is this supposed to be a singleton?
yes

2022-05-06 10:46 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +    repo?: string;
I looked at the ticket and asked around for what this property looks like and it's used.
It seems that it would be used by Amplitude to link events to a Repository.

Knowing that, I asked François and Tony about how to use it properly making sure we don't use it the wrong way.

On an event, it should look like this.
```
  "context": {
    "groupId": {
      "Repository": ....
   }
```

After looking at how analytics is made for SliceMachine, we can add a context object on every tack call.

For that, we would need to add a new internal property to the tracker -> `repository`
And then we can use it on every track event call that we make.

2 things tho
- the repository property must be given on initialisation (backend + frontend + init ?)
- the repository property must be updated whenever we detect a changes in the SM.json (i guess that would only be for the frontend)

2022-05-06 10:48 UTC, MarcMcIntosh commented on packages/slice-machine/components/Forms/CreateCustomTypeModal.tsx
> +    // notes repo name could be empty, and will the tracker be initialized?
Things to look into.

The tracker should be initialised in `_app.tsx` not sure about which cases would cause the repo to be null

2022-05-06 10:49 UTC, MarcMcIntosh commented on packages/slice-machine/src/tracker.ts
> +  trackCreatCustomType(customTypeInfo: {
typo... pretty sure my keyboard needs a clean.

2022-05-06 11:09 UTC, MarcMcIntosh commented on packages/slice-machine/src/tracker.ts
> +// is this supposed to be a singleton?
Could also be done this way

```
class Singleton {
  count: number;
  private static instance: Singleton;

  private constructor() {
    this.count = 0
  }
  
  static getInstance(): Singleton {
    if (!Singleton.instance) {
      Singleton.instance= new Singleton();
    }
    return Singleton.instance;
  }
  
  log() {
    console.log("Hello " + this.count)
    this.count++
  }
}

 var a = Singleton.getInstance()
 var b = Singleton.getInstance()
 a.log()
 b.log()
 b.log()
 a.log()

```

2022-05-06 11:56 UTC, MarcMcIntosh commented on packages/slice-machine/src/tracker.ts
> +    repo?: string;
Should that not have been done before estimating the ticket?

2022-05-06 12:13 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +    repo?: string;
I guess you are right 😄.
It was added to a ticket not really knowing the subject I guess.

Here's the investigation to make it true 😉

2022-05-06 12:14 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +// is this supposed to be a singleton?
Yes I guess so, but in the end it would give the same result no ?

2022-05-06 12:14 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +  trackCreatCustomType(customTypeInfo: {
haha, happens

2022-05-06 12:15 UTC, Heyrows commented on packages/slice-machine/components/Forms/CreateCustomTypeModal.tsx
> +    // notes repo name could be empty, and will the tracker be initialized?
I guess the repo is null until the redux store is initialised 😄.

2022-05-06 12:16 UTC, Heyrows commented on packages/slice-machine/components/Forms/CreateCustomTypeModal.tsx
> +    // notes repo name could be empty, and will the tracker be initialized?
What I mean was more like.
If there is a comment, does it means that the work is not finished ?
Or it is a side comment about another subject ?

In that last case, is a comment the better way to retain the information and discuss about it ?

2022-05-06 15:01 UTC, Heyrows requested changes

2022-05-06 15:01 UTC, Heyrows commented on packages/slice-machine/src/tracker.ts
> +    repo?: string;
You forgot this :)

2022-05-09 08:43 UTC, Heyrows approved these changes

2022-05-09 09:09 UTC, merged