Cleanup package.json scripts
prismicio/slice-machine pull request #697
Opened 2022-11-22 11:46 UTC by danigo99

## Context

Removing unused scripts from all package.json, and cleaning up remaining ones.
Ticket: https://linear.app/prismic/issue/SM-850/[tech-debt]-aacontributor-i-see-only-the-used-scripts-in-the-project

## The Solution

## Impact / Dependencies

## Checklist before requesting a review
- [ ] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

---

![image](https://user-images.githubusercontent.com/47107427/203306238-f8e3e790-e843-4337-aeba-8ec5ef702404.png)

2022-11-22 12:38 UTC, danigo99 commented
Where remaining scripts are used:

### Root
`cypress-setup` - (CI & dev) sets up e2e project before cypress e2e tests
`clean-e2e-projects` - (dev) helper script for cleaning changes to the e2e project during dev
`prepare` - (CI & dev) executed after npm i
`postinstall` - bootstraps the project and installs deps in e2e project
`bootstrap` - bootstraps the whole project
`build-essential` - (CI) builds core & client packages
`audit` - (CI) runs npm audit checks
`lint` - linting
`lint-staged` - (pre-commits) runs linting on staged changes
`prettier:check` - (CI) prettier checks 
`test` - (CI & dev) runs tests
`test:e2e` - (CI & dev) runs e2e tests
`test:e2e:dev` - (dev) runs e2e tests in dev mode
`bump:alpha` - (CI) used in alpha releases
`publish:alpha` - (CI) used in alpha releases
`publish:production` - used in manual prod releases
`bump:production` - used in manual prod releases
`bump:interactive` - used after release process to bump version
`depcheck` - (CI) used to check project dependencies

### Slice-machine
`dev` - (dev) launches next project
`test` - (CI & dev) runs tests in normal mode
`test:watch` - (dev) runs tests in watch mode (alias during dev)
`clean-build` - removes the client built on pre-publish
`postinstall` - runs postinstall script after npm i
`dev-server` - (dev) starts the dev server
`build` - (CI & dev) builds the package
`build-scripts` - builds the scripts folder
`build-server` - builds the server
`build-next-app` - builds the next app
`export-build` - exports next project & runs clean-build
`bundle` - runs build + export build
`lint` - runs linting
`lint:precommit` - runs linting on staged changes
`audit` - runs npm audit checks
`audit-fix` - fixes npm audit check
`depcheck` - (CI) used to check project dependencies

### Other
`build` - builds the relevant package
`tsc:watch` - runs TS checks in watch mode on relevant package
`tsc` - runs TS checks on relevant package
`lint` - runs linting on relevant package
`lint:precommit` - runs pre-commit lints on relevant package
`audit` - runs audit checks on relevant package
`audit`-fix - fixes npm audit issues on relevant package
`test` - runs unit tests on relevant package
`depcheck` - checks dependencies  on relevant package
`prepublishOnly` - auto-run after `publish:alpha` to test + build relevant packages

2022-11-22 14:52 UTC, danigo99 commented on packages/client/package.json
> -    "prepublishOnly": "npm run test && npm run build",
@Heyrows @MarcMcIntosh do you use this during releases?

2022-11-22 15:28 UTC, danigo99 commented on packages/client/package.json
> -    "prepublishOnly": "npm run test && npm run build",
Mathieu just told me it's automatically run on `publish:alpha`

2022-11-22 17:01 UTC, Heyrows requested changes
seems good beside the prepublishonly

2022-11-22 17:01 UTC, Heyrows commented on package.json
> -    "pretty": "prettier --write .",
are we sure we want to remove that ?

2022-11-22 17:01 UTC, Heyrows commented on package.json
> -    "pretty": "prettier --write .",
or is it too simple to be used.

2022-11-22 17:01 UTC, Heyrows commented on packages/slice-machine/package.json
> +    "prepublishOnly": "npm run test && npm run build",
not good, bundle does the build and export it (changing the folders and all), I believe this will not work.

2022-11-22 17:01 UTC, Heyrows commented on packages/client/package.json
> +    "tsc:watch": "tsc --project tsconfig.json --noEmit --watch",
seems nice, a good improvement for the future would be to run all of them except SM in watch mode.
i'm sure @bapmrl would have nice inputs about it.

2022-11-22 17:04 UTC, danigo99 commented on packages/slice-machine/package.json
> +    "prepublishOnly": "npm run test && npm run build",
Nice catch, this was a mistake

2022-11-22 17:04 UTC, danigo99 commented on package.json
> -    "pretty": "prettier --write .",
It's not used anywhere but I guess it wouldn't hurt to keep it. might be useful

2022-11-23 09:03 UTC, Heyrows approved these changes

2022-11-23 09:43 UTC, merged