port sentry tunnel to plugins
prismicio/slice-machine pull request #861
Opened 2023-03-08 10:23 UTC by mathieud

## Context

Current implementation: https://github.com/prismicio/slice-machine/blob/6fcf51a1fbc478357318f7109c7c0ad3a3374963/packages/slice-machine/server/src/api/sentry.ts

## The Solution

## Impact / Dependencies

## Checklist before requesting a review
- [ ] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

## [OPT] Preview

2023-03-08 10:48 UTC, hypervillain requested changes

2023-03-08 10:48 UTC, hypervillain commented on packages/start-slicemachine/src/lib/sentry.ts
> +const axios = require("axios");
Is there a reason to use `require` over `import`?

2023-03-08 15:34 UTC, hypervillain approved these changes

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/createSliceMachineServer.ts
> +import { default as sentryHandler } from "./sentryHandler";
💡 I'm not sure Lucie and Angelo used default exports in the plugins PR and I personally think it's not good to use them. Named exports provide one consistent way of importing modules in TypeScript.

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +// We tunnel the Sentry calls via the express server to avoid add blockers
❓ Is it Express or `h3`?

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +// We tunnel the Sentry calls via the express server to avoid add blockers
⚠️ "ad blockers" rather than "add blockers".

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +import * as url from "url";
💡 Let's not use wildcard imports to avoid importing unnecessary functions (which could lead to increased bundle sizes).

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +async function handler(event: H3Event): Promise<Record<string, never>> {
❓ Would `Promise<void>` or `Promise<unknown>` work to simplify the return type?

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +		// TODO add this back when we have the express
❓ What should be done with this `TODO`?

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +// adapted from https://github.com/getsentry/examples/blob/master/tunneling/nextjs/pages/api/tunnel.js
⚠️ That URL is broken. You could use the `Y` shortcut mentioned by Angelo to create a canonical URL ^^

2023-03-08 15:47 UTC, bapmrl commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +		const sentryUrl = `https://${host}/api/${projectId}/envelope/`;
❓ What happens if `projectId` is `""`? It would go inside the `catch` and do nothing?

2023-03-09 09:51 UTC, mathieud commented on packages/start-slicemachine/src/lib/sentry.ts
> +const axios = require("axios");
Got an error similar to `https://github.com/axios/axios/issues/4231`, and one comment mentioned using `require` instead would work. I tried and it did.
Not sure what the root cause is though

2023-03-09 09:51 UTC, mathieud commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +async function handler(event: H3Event): Promise<Record<string, never>> {
Sentry returns `{}` on success, wanted to keep the same behavior

2023-03-09 09:51 UTC, mathieud commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +		// TODO add this back when we have the express
I'm working on it :-)

2023-03-09 09:51 UTC, mathieud commented on packages/start-slicemachine/src/lib/sentryHandler.ts
> +		const sentryUrl = `https://${host}/api/${projectId}/envelope/`;
@bapmrl Will handle this with the server part of Sentry

2023-03-09 09:53 UTC, bapmrl approved these changes

2023-03-10 10:38 UTC, merged