Backport types internal
prismicio/slice-machine pull request #911
Opened 2023-04-07 10:03 UTC by hypervillain

- Use alpha (latest) version of @prismicio/types-internal, @prismicio/mocks editor-fields and editor-ui everywhere
- Replace types with types-internal everywhere

2023-04-11 08:15 UTC, arnaudlewis commented
Don't forget the backport the rest regarding the mock config of date and link that are new in editor 0.3.0.

2023-04-11 09:20 UTC, lihbr requested changes
LGTM, just some small things.

Could you have a look at backporting the date & link from editor 0.3.0 as Arnaud mentioned? (this PR or another, whatever works best for you)

2023-04-11 09:20 UTC, lihbr commented on package.json
> +    "@prismicio/mocks": "^2.0.0-alpha.2",
Why does `@prismicio/mocks` needs to be installed top level?

2023-04-11 09:20 UTC, lihbr commented on packages/manager/test/lib-mockSlice.test.ts
> +		expect(isRight(geoR)).toBeFalsy();
This should be truthy no? You likely need to uncomment line 25

Left as is (as I understand it) it defeats the purpose of the test (which also has no reason to be a test in first place here, we shouldn't have to test types-internal here)

2023-04-11 09:20 UTC, lihbr commented on packages/slice-machine/components/Select/index.tsx
> +// }
If this is not needed anymore, maybe you can just get rid of it?

2023-04-12 14:06 UTC, lihbr approved these changes

2023-04-13 09:17 UTC, merged